### ISSUE TITLE
Images not shown on the home page.

### ISSUE THREAD

**Issue by Egonyu** [aimeos/aimeos#10]
Hello here,
Appreciate the package very much, i wanted to use the package for my site but am stuck at this point.
Am sorry to be here with this question as i see no one has come across it,
But i successfully installed the package, created a few products but then i don't see the product images appear on the product list.

The images are somehow stored the public directory under preview folder.
So am wondering how do i get them to show up on the site pages.

Am using windows 10 x64, php 7.2, using the official documentation.
![aimeo](https://user-images.githubusercontent.com/24682769/47823517-c0c94f80-dd79-11e8-8088-e06036ce8141.PNG)
![aimeos](https://user-images.githubusercontent.com/24682769/47823518-c161e600-dd79-11e8-8a1e-470c13bb740f.PNG)

Thanks in advance.

**Comment by aimeos** [comment]
To see your uploaded images, you have to adapt your `.env` file and set the `APP_URL` if you use `127.0.0.1:8000` as base URL (the port `8000` is important):

```APP_URL=http://127.0.0.1:8000```

**Comment by Egonyu** [comment]
Thanks alot it worked you can't believe the smile on my face. I couldnt hide it.
Awesome. So i if i uploaded it to my share server there is not going to be an issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Egonyu** [comment]
Am trying to also change the prices to local currency of UGX but it not working

**Comment by aimeos** [comment]
Go to the "Locale" panels in the admin interface and make sure the site/language/currency combination you want is the first one in the locale panel

**Comment by Egonyu** [comment]
Thank you Alot
