### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by v1cc** [aimeos/aimeos#102]
I did a fresh install and I am having an issue login into the admin panel, it gives me this error when I try to log in. 

app / Http / Middleware/ SetLocale.php: 25

error on this line -> return $next($request);

A non-numeric value encountered

Please help, Thank you.

**Comment by aimeos** [comment]
Do you have a full stack trace?

**Comment by v1cc** [comment]
> Do you have a full stack trace?

![Screen Shot 2023-01-03 at 3 00 25 PM](https://user-images.githubusercontent.com/3595636/210326510-1513167c-ab8e-4ac7-9e7b-4f62f974de9f.png)

Does this help?

**Comment by aimeos** [comment]
No. Can you share the stack trace on Flare (share button at the top)?

**Comment by v1cc** [comment]
> No. Can you share the stack trace on Flare (share button at the top)?

Sorry, here is the link

https://flareapp.io/share/87noqjM5#F68

**Comment by aimeos** [comment]
You seem to have an invalid setting for `post_max_size` or `upload_max_filesize`. Can you please check what are the values for them?

**Comment by v1cc** [comment]
> post_max_size

I got it fixed, Thank you
