### ISSUE TITLE
Xdebug porblem

### ISSUE THREAD

**Issue by daalvand** [aimeos/aimeos#105]
Hello,

Are there any known issues or limitations when using Aimeos, with Xdebug? I am currently working on a project that utilizes both Aimeos and Xdebug and I have noticed some unexpected behavior the application crashed on the shop page.

**Comment by aimeos** [comment]
XDebug is only for testing and depending on your XDebug (default) settings, it may break the requests because there are more methods called that allowed by the XDebug configuration.

**Comment by daalvand** [comment]
> XDebug is only for testing and depending on your XDebug (default) settings, it may break the requests because there are more methods called that allowed by the XDebug configuration.

I'm familiar enough with xdebug to know how to use it and know if debug mode is off or not.
