### ISSUE TITLE
Page item not foundf: admin/default/jqadm/search/dashboard?locale=en 

### ISSUE THREAD

**Issue by cgcmart** [aimeos/aimeos#106]
Aimeos  \  MShop  \  Exception
No item found for conditions: Array ( [locale.site.code] => default )
App \ Http \ Middleware \ SetLocale: 25 handle
`return $next($request);`

![aimeos_error1](https://user-images.githubusercontent.com/14033183/227730766-31b6440b-b699-4e2a-94ed-a7a83d36e04c.jpg)

![aimeos_error1-1](https://user-images.githubusercontent.com/14033183/227731402-82c7de69-58e6-450f-b12d-070d9884ae2d.jpg)

**Comment by aimeos** [comment]
Either the Aimoes setup failed or you've removed the `default` site or renamed the `default` site without configuring the new site name with should be used by default.

Did you get any errors during setup?

**Comment by cgcmart** [comment]
no, setup smoothly. I successfully logged in admin and familiarized with aimeos for a while. and changed home page colors.
front pages look good and impressive.
a couple of days ago I installed extensions "aimeos/ai-cms-grapesjs", "aimeos/ai-cache", "aimeos/ai-catsuggest", and "aimeos/ai-filesystem"

Today, I wanted to log in admin and do something cms contents. But either admin or front has the same exception error.

**Comment by aimeos** [comment]
The `SetLocale` middleware is only the first one which fetches the `default` site item. Check the rows in the `mshop_locale_site` table what is available there and post it's contents, please.

**Comment by cgcmart** [comment]
> The `SetLocale` middleware is only the first one which fetches the `default` site item. Check the rows in the `mshop_locale_site` table what is available there and post it's contents, please.

There is 1 row:
```
`mshop_locale_site` (`id`, `parentid`, `siteid`, `code`, `label`, `icon`, `logo`, `config`, `refid`, `theme`, `level`, `rating`, `ratings`, `invoiceno`, `nleft`, `nright`, `status`, `mtime`, `ctime`, `editor`) VALUES
(1, 0, '1.', 'wenbo.world', 'Wenbo', '1.d/icon.png', '{\"1\":\"1.d\\/logo.png\"}', '{\"resource\":{\"email\":{\"from-email\":\"dotcom@china-guide.com\",\"from-name\":\"Wenbo\"}},\"theme\":{\"default\":{\"--ai-product-image-ratio\":\"3\\/4\",\"--ai-bg\":\"#ffffff\",\"--ai-bg-alt\":\"#ffffcc\",\"--ai-primary\":\"#669933\",\"--ai-primary-alt\":\"#99cc33\",\"--ai-secondary\":\"#99cc66\",\"--ai-secondary-alt\":\"#7d7d2d\",\"--ai-tertiary\":\"#f7a586\",\"--ai-tertiary-alt\":\"#f6f6f6\",\"--ai-danger\":\"#a00000\",\"--ai-success\":\"#006000\",\"--ai-warning\":\"#ffa500\",\"--ai-radius\":\"0\"}}}', '', 'default', 0, '0.00', 0, 1, 1, 2, 1, '2023-03-18 20:12:16', '2023-03-12 16:28:20', 'dotcom@china-guide.com');
```

**Comment by aimeos** [comment]
You've renamed the site code from `default` to `wenbo.world`. This is only OK if you configure:
- domain based routing (https://aimeos.org/docs/latest/laravel/customize/#adapt-the-routing)
- new default site (https://github.com/aimeos/aimeos/blob/master/config/shop.php#L208)

**Comment by cgcmart** [comment]
@aimeos Thank you very much! aimeos does a wonderful job. I prefer aimeos to typo3.
