### ISSUE TITLE
Installation on clean Laravel 10

### ISSUE THREAD

**Issue by arianmasselink** [aimeos/aimeos#107]
I've just installed a clean Laravel 10 and tried to add your newest version. I get following error when I composer require:

composer require aimeos/aimeos-laravel:~2023.04.1
./composer.json has been updated
Running composer update aimeos/aimeos-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-diactoros[2.5.0, ..., 2.6.0] require php ^7.3 || ~8.0.0 -> your php version (8.1.18) does not satisfy that requirement.
    - laminas/laminas-diactoros[2.7.0, ..., 2.24.2] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but it conflicts with your root composer.json require (^2.0).
    - laminas/laminas-diactoros[2.25.0, ..., 2.25.2] require psr/http-message ^1.1 -> found psr/http-message[1.1] but it conflicts with your root composer.json require (^2.0).
    - aimeos/aimeos-laravel 2023.04.1 requires laminas/laminas-diactoros ~2.5 -> satisfiable by laminas/laminas-diactoros[2.5.0, ..., 2.25.2].
    - Root composer.json requires aimeos/aimeos-laravel ~2023.04.1 -> satisfiable by aimeos/aimeos-laravel[2023.04.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Could somebody help me with this?

**Comment by arianmasselink** [comment]
Fixed it by downgrading psr/http-message from ^2.0 to ^1.1

**Comment by kras95** [comment]
> Fixed it by downgrading psr/http-message from ^2.0 to ^1.1

Thank you, that worked 👍
