### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by muhammadsufi** [aimeos/aimeos#11]
i got below error after i create fresh project "composer create-project aimeos/aimeos myshop"

Creating base tables                                                  
  Using schema from locale.php                                        
    Checking table "mshop_locale_site":                               
In MySqlSchemaManager.php line 315:
                                                                               
  Type error: Argument 1 passed to Doctrine\DBAL\Schema\MySqlSchemaManager::p  
  arseCreateOptions() must be of the type string, null given, called in /User  
  s/sufi/Documents/Work/GitHub/myshop/vendor/doctrine/dbal/lib/Doctrine/DBAL/  
  Schema/MySqlSchemaManager.php on line 307

**Comment by aimeos** [comment]
That's a bug in the current Doctrine DBAL library (2.9.1): https://github.com/doctrine/dbal/issues/3410
We've added a constraint to avoid that version. Can you try again?

**Comment by muhammadsufi** [comment]
Wahh.. so fast reply.. okay i'll try tonight.. thanks alot with this fast
assist.. I'll update if got any other error

**Comment by muhammadsufi** [comment]
Hi, i still got the same error

**Comment by aimeos** [comment]
Did you run `composer update` on your existing installation or did you create a new one with `composer create-project aimeos/aimeos myshop`?

Can you post the output of `composer show`?

**Comment by muhammadsufi** [comment]
i create another fresh project

**Comment by aimeos** [comment]
composer ignores the requirement in the latest aimeos-core packages and installs the previous version instead which doesn't limit doctrine/dbal to <2.9.1. The only was to be sure composer uses that requirement was to add it to the composer.json file of the Aimeos package itself.

We've released a new version 2018.10.2 which now enforces the correct DBAL version.

**Comment by kalazzar** [comment]
Awesome..it works now..thanks for the assist
