### ISSUE TITLE
Unable to customize the error messages?

### ISSUE THREAD

**Issue by shainanand23** [aimeos/aimeos#110]
In admin, when I am trying to add a locale site, if it is a duplicate entry then it will throw error "Error saving data". But the message is generic. How can I customize this error message for specific fields?

**Comment by aimeos** [comment]
When registering, you can catch the exception here: https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L69

**Comment by shainanand23** [comment]
But the exception generated is Aimeos\Base\DB\Exception. Is there any way to know which field caused the error? @aimeos

**Comment by aimeos** [comment]
There's no way to get the specific field for the error if you don't check it upfront but in 99% of all cases you get an error if the code is not unique

**Comment by shainanand23** [comment]
In the validation language file, there are some options for custom validation in the language file. Will it work if the field is assigned a custom attribute?

![image](https://github.com/aimeos/aimeos/assets/73652633/fb1530c8-8820-4b7b-b144-e8458508630b)

**Comment by shainanand23** [comment]
Another question, may I know where is the file where I can put validation rules before the site details are saved? If i can find that file, I can put custom validation rules there right?

**Comment by shainanand23** [comment]
Also, this is related to Aimeos Laravel package @aimeos

**Comment by aimeos** [comment]
For support questions, please open a new topic in the Aimeos forum: https://aimeos.org/help
Github issues are only for bug reports and feature requests
