### ISSUE TITLE
Need to create new route in jqadmin

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#111]
How can create new route in jqadm interface?
As I am implementing an additional functionality in Customers module.
Now getting Route [] not defined. error while adding link in detail page.
@aimeos

**Comment by unnimaya-seeroo** [comment]
Planned to add a approval functionality for users (sellers) in admin detail page.
So I added link , by clicking that some database operation will be done , after that redirect to the same page with success message @aimeos

**Comment by aimeos** [comment]
No need to create a new route/controller for that if you stay within the admin backend. The "save" route is enough and if you only want to perform some database operations in addition, you can create a decorator with your code that does its job depending on the parameters you hand over:
https://aimeos.org/docs/latest/admin/jqadm/extend-panels/

If you have more questions, please open a new topic in the Aimeos forum for help: https://aimeos.org/help
