### ISSUE TITLE
.jpg files are not get uploaded , showing image type is not supported by GDlib

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#112]
Have trouble with saving photos here for the category slider photos. It seems that I can save .png files, but not .jpg or .jpeg les. I know there is a 2MB file size limit, but I cannnot figure out why I get this error message with the .jpg files that I want to use here.
@aimeos

**Comment by aimeos** [comment]
Using JPEG files is allowed and should work without problems if they doesn't exceed the PHP file upload size limit. If the files are bigger, change the PHP configuration to allow bigger files.
