### ISSUE TITLE
HTML style attributes not get saved 

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#113]
Trying to add css atributes in text section.
Catelog->category->Text
But once saved the color attribute not get save and reflected , pls advice
![NPK-Marketplace-Account-Management (1)](https://github.com/aimeos/aimeos/assets/83745002/dc201162-4b50-4595-bc39-a8ba3c5d6996)
@aimeos

**Comment by aimeos** [comment]
CKEditor 5 doesn't allow custom styles in HTML tags by default. You have to customize CKEditor like described here:
https://aimeos.org/docs/latest/admin/jqadm/customize/#ckeditor
