### ISSUE TITLE
How can save site details when editing customer detail?

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#114]
About to create a site for a user while enable a user through customer detail page.
so i need to save site data such as status, code,label ..
Included site manager in customer standard.php
showing 
Aimeos\MShop\Locale\Manager\Site\Standard::saveItem(): Argument #1 ($item) must be of type Aimeos\MShop\Locale\Item\Site\Iface, Aimeos\MShop\Customer\Item\Standard given, called in D:\xampp12\htdocs\npkmarket\vendor\aimeos\aimeos-core\src\MShop\Common\Manager\Methods.php on line 259.
@aimeos 
Customer standard.php/Save function
public function save() : ?string
	{
		$view = $this->view();
		$manager = \Aimeos\MShop::create( $this->context(), 'customer' );
		$manager->begin();

		$site_manager = \Aimeos\MShop::create( $this->context(), 'locale/site' );
		$site_manager->begin();
		try
		{
			$items = $view->param( 'item', [] );

			//creat custom request object and validate it and pass back as exception
			$request = new \Illuminate\Http\Request();

			$request->replace(['email' =>  $items['customer.email']]);

			$rules = [
			            'email' => ['unique:users,email,'.$items['customer.id'].''],
			        ];

			$request->validate($rules);

			$item = $this->fromArray( $view->param( 'item', [] ) );
			$view->item = $item->getId() ? $item : $manager->save( $item );
			dd($view->item);
			$view->itemBody = parent::save();

			$manager->save( clone $view->item );
			$manager->commit();
			
			$site_array = array(
				"locale.site.status" => 1,
				"locale.site.code" => "newcd",
				"locale.site.label" => "tania",
				"locale.site.config" => [],
				"locale.site.siteid" => "1.56.");
			$site_manager->save( $site_array,true);
			$site_manager->commit();
			return $this->redirect( 'customer', $view->param( 'next' ), $view->item->getId(), 'save' );
		}
		catch( \Exception $e )
		{
			$manager->rollback();
			$this->report( $e, 'save' );
		}

		return $this->create();
	}

**Comment by aimeos** [comment]
Please ask non-bug/feature request questions in our Aimeos forum:
https://aimeos.org/help
