### ISSUE TITLE
Product detail not reflecting

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#116]
I have added some data in Physical menu for a product , it will not get reflected in product detail page in front end
![image](https://github.com/aimeos/aimeos/assets/83745002/b2c27193-a47d-4ed9-888d-e6941ffe90c5)
@aimeos

**Comment by aimeos** [comment]
Package length/width/height/weight are shown in the characteristics tab of the detail page:
https://laravel.demo.aimeos.org/shop/dark-grey-dress/0
