### ISSUE TITLE
No user detail page in subuser login

### ISSUE THREAD

**Issue by unnimaya-seeroo** [aimeos/aimeos#119]
I have created a new site by using locale/site and added one user .
Loggined with the user created, got the dashboard panel, I could not find any account page there.
Do any profile page for log in user in aimeos ?? @aimeos

**Comment by aimeos** [comment]
If users have super/admin/editor privileges, then they are redirected to the admin backend. They also have a profile page in the frontend available via the user icon in the page header at the top right.
