### ISSUE TITLE
Demo data processing error

### ISSUE THREAD

**Issue by jithincubet** [aimeos/aimeos#12]
Showing the following error during the setup.

`  Adding default attribute data for site "default"                      1/1                 
  Adding default plugin data                                                                
    Adding data for MShop plugins                                       11/11               
  Processing coupon demo data                                           added               
  Adding default code data for site "default"                                               
    Checking "customer/group" codes                                     2/2                 
  Processing service demo data                                          added               
  Processing customer demo data                                         added               
  Processing product demo data                                                              
  In Simple.php line 91:                                                                    
                                                                                            
    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-pr             
    oduct-custom-8' for key 'unq_msattr_sid_dom_cod_tid'                                    
                                                                                            
  Error Output:                                                                             
  ================                                                                  `

**Comment by aimeos** [comment]
You are right, the "custom" price attribute is tried to be added twice during setup. We will fix that and come back to you soon.

**Comment by aimeos** [comment]
Problem has been fixed and a new version released
