### ISSUE TITLE
502 Error when Enabling SHOP_MULTILOCALE and custom domain

### ISSUE THREAD

**Issue by VS3-RATINA** [aimeos/aimeos#121]
## Summary

Getting 502 Bad Gateway error when enabling SHOP_MULTISHOP in .env

## Steps to reproduce

1. Set `SHOP_MULTISHOP=true` and `SHOP_MULTILOCALE=true` in `.env`
2. Try to access site like `https://example.com/en`
3. 502 error returned, no errors logged in `storage/logs/laravel.log`

## Expected behavior

Site should load successfully even with SHOP_MULTISHOP enabled.

## Actual behavior

502 Bad Gateway error returned when trying to access site with locale prefix. No errors logged. ( even on `storage/logs/laravel.log` ) 

## Configuration

- OS: Linux , ubuntu
- Web server:nginx
- PHP version:8.2

## Relevant code

config/web.php:
```
<?php

use Illuminate\Support\Facades\Route;

$params = [];
$conf = ['prefix' => '', 'where' => []];

if( env( 'SHOP_MULTILOCALE' ) )
{
    $conf['prefix'] .= '{locale}';
    $conf['where']['locale'] = '[a-z]{2}(\_[A-Z]{2})?';
    $params = ['locale' => app()->getLocale()];
}


if( $conf['prefix'] )
{
    Route::group(['domain' => '{site}', 'middleware' => ['web']], function () {
        Route::get('/', '\Aimeos\Shop\Controller\CatalogController@homeAction')
             ->name('aimeos_home')->where( ['site' => '[a-z0-9\-]+'] );
    });
}

Route::group($conf ?? [], function() {
    require __DIR__.'/auth.php';
});


// custom domain: vendor1.com
Route::group(['domain' => '{site}', 'middleware' => ['web']], function () {
    Route::match(['GET', 'POST'], '{path?}', '\Aimeos\Shop\Controller\PageController@indexAction')
        ->name('aimeos_page')->where( 'path', '.*' )->where( ['site' => '[a-z0-9\.\-]+'] );
});


```

config/shop.php:
```<?php

$routes = [];
$prefix = config( 'app.shop_multilocale' ) ? '{locale}/' : '';
if( config( 'app.shop_multishop' ) ) {
	$routes = ['routes' => [
		'admin' => ['prefix' => 'admin', 'middleware' => ['web']],
		'jqadm' => ['prefix' => 'admin/{site}/jqadm', 'middleware' => ['web', 'auth', 'verified']],
		'jsonadm' => ['prefix' => 'admin/{site}/jsonadm', 'middleware' => ['web', 'auth', 'verified']],=
		'graphql' => ['domain' => '{site}', 'prefix' => 'admin/graphql', 'middleware' => ['web', 'auth']],		
		'jsonapi' => ['domain' => '{site}', 'prefix' => 'jsonapi', 'middleware' => ['web', 'api']],
		'account' => ['domain' => '{site}', 'prefix' => 'profile', 'middleware' => ['web', 'auth']],
		'default' => ['domain' => '{site}', 'prefix' => 'shop', 'middleware' => ['web']],
		'update' => ['domain' => '{site}'],
		'home' => ['domain' => '{site}', 'middleware' => ['web']],
		'page' => ['domain' => '{site}/p', 'middleware' => ['web']],
		'supplier' => ['domain' => '{site}/s', 'middleware' => ['web']],
	] ];
....
```

.env:

```
SHOP_MULTILOCALE=true
SHOP_MULTISHOP=true 
```

Let me know if any other config or code snippets would be helpful!

**Comment by VS3-RATINA** [comment]
i replaced those 2 lines , but still `502 Error` * no errors logged

**Comment by aimeos** [comment]
Another problem: For `https://example.com/en`, the site code of the default site must be `example.com` (by default, it's `default`)

**Comment by VS3-RATINA** [comment]
@aimeos I don't forget to set a custom domain for all existing sites

**Comment by aimeos** [comment]
Set `APP_DEBUG=true` in your `.env` file and see if there's an error displayed in the frontend

**Comment by VS3-RATINA** [comment]
Is already set. APP_DEBUG=true 
_Note: I use Cloudflare. Can that affect the error logger?_

**Comment by aimeos** [comment]
Yes, then the 502 page is from Cloudflare and the real problem is hidden

**Comment by VS3-RATINA** [comment]
@aimeos 
Also get 502 error (without Cloudflare)
[![JJmWM3g.md.png](https://iili.io/JJmWM3g.md.png)](https://freeimage.host/i/JJmWM3g)
I'm sure the problem is within **shop.php or web.php or maybe (app/Http/Middleware/SetLocale.php)**, because it's not happening when on prefix mode shop.

**Comment by aimeos** [comment]
Have a look into the PHP FPM logs for details

**Comment by VS3-RATINA** [comment]
error_log file i found it empty ,

```
username@localhost:~/workshop/<project>$ php artisan serve --port=XXXX

   INFO  Server running on [http://127.0.0.1:XXXX].  

  Press Ctrl+C to stop the server

  2023-09-28 08:29:05 ............................................................................................................ ~ 0s
```

On 2023-09-28 at 08:29:05, I tried to visit https://example.com/en

my app/Http/Middleware/SetLocale.php : 
```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class SetLocale
{
	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	
 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle(Request $request, Closure $next)
	{
		if( env( 'SHOP_MULTILOCALE' ) && ( $locale = $request->segment( 1 ) ) !== null
			&& preg_match( '/^[a-zA-Z]{2}(\_[a-zA-Z]{2})?$/', $locale )
		) {
			app()->setLocale( $locale );			
		}
		return $next($request);
	}
}
```

**Comment by aimeos** [comment]
Is there a Laravel error page available you can share (top right "Share" button)?

**Comment by VS3-RATINA** [comment]
@aimeos 
[![JJmWM3g.md.png](https://iili.io/JJmWM3g.md.png)](https://freeimage.host/i/JJmWM3g)
Just encountered a 502 Bad Gateway error on a white page, similar to what I shared in the previous comment

**Comment by aimeos** [comment]
OK, but that's no help to find the problem.
