### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by kawsarujjaman** [aimeos/aimeos#122]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myshop.mshop_locale_site' doesn't exist: SELECT mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."icon" AS "locale.site.icon", mlocsi."logo" AS "locale.site.logo", mlocsi."rating" AS "locale.site.rating", mlocsi."ratings" AS "locale.site.ratings", mlocsi."refid" AS "locale.site.refid", mlocsi."theme" AS "locale.site.theme", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" mlocsi WHERE ( mlocsi."code" = 'default' ) ORDER BY mlocsi."id" ASC LIMIT 1 OFFSET 0

**Comment by aimeos** [comment]
Have there been any errors during setup? Seems like the database tables haven't been created

**Comment by kawsarujjaman** [comment]
Thank you. It's now working
