### ISSUE TITLE
Error Encountered When Creating a New Account 

### ISSUE THREAD

**Issue by Alababdiy** [aimeos/aimeos#124]
I encountered an error when attempting to register a new account through one of the stores. The error I received is as follows:

```
Call to undefined function mb_strcut() in resources/views/vendor/mail/html/layout.blade.php:41
```

Additionally, instead of registering a new account, it seems to be creating a new site.

My environment settings related to this issue are as follows:

```
SHOP_MULTISHOP=1
SHOP_REGISTRATION=1
```

The code snippet where the error occurred is highlighted below:

```html
<!-- Email Body -->
<tr>
    <td class="body" width="100%" cellpadding="0" cellspacing="0">
        <table class="inner-body" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation">
            <!-- Body content -->
            <tr>
                <td class="content-cell">
                    {{ Illuminate\Mail\Markdown::parse($slot) }} // ERROR HERE‼!!!!!!!!! 
                    {{ $subcopy ?? '' }}
                </td>
            </tr>
        </table>
    </td>
</tr>
```

This issue arises during the process of creating a new account but unexpectedly generates a new site.

Is happening on URL
```
https://{site-url}/register?site={site-url}
```

**Comment by aimeos** [comment]
On your server, the `mb_string` PHP extension is missing

**Comment by aimeos** [comment]
Registration is configured for vendors and creates a new site in the distribution. Customer accounts are registered at the end of the checkout process automatically if not checked off.
