### ISSUE TITLE
Base table or view not found: 1146 Table 'homestead.mshop_locale_site' doesn't exist"

### ISSUE THREAD

**Issue by Jbeard822** [aimeos/aimeos#13]
Super excited to use your shop, but ran into an issue. I went through the installation process, set up the .env file, then checked the serve, it showed http://127.0.0.1:8000 as expected. However upon opening this on the browser I got the following error:

![aimeos shop error](https://user-images.githubusercontent.com/35740669/50942547-ab923080-144e-11e9-9f45-49f353835825.PNG)

Haven't figured out how to get around this. Any help you can give would be great, thanks!

**Comment by aimeos** [comment]
The database setup process hasn't been executed for some reason or stopped with an error. Do you still have the output of the installation?

**Comment by Jbeard822** [comment]
Thank you for your rapid response. I do have the output from the installation, I am showing the beginning and end, the middle all looks correct, let me know if you need another snippet:

composer create-project aimeos/aimeos myshop
Installing aimeos/aimeos (2018.10.2)
  - Installing aimeos/aimeos (2018.10.2): Loading from cache
Created project in myshop
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "mkdir('public/files'); mkdir('public/preview'); mkdir('public/uploads');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 89 installs, 0 updates, 0 removals


.......

Publishing complete.
> @php artisan key:generate
Application key [base64:Mot9rlX8PTc32cgaL/W6LFMyLrNoA1MzIIG4a/AXnCk=] set successfully.
> @php artisan make:auth
Authentication scaffolding generated successfully.
> App\Composer::configure
Database setup
- DB_CONNECTION (mysql): mysql
- DB_HOST (127.0.0.1): 127.0.0.1
- DB_PORT (3306): 3306
- DB_DATABASE (homestead): homestead
- DB_USERNAME (homestead): homestead
- DB_PASSWORD:
Mail setup
- MAIL_DRIVER (smtp): smtp
- MAIL_HOST (smtp.mailtrap.io): smtp.mailtrap.io
- MAIL_PORT (2525): 2525
- MAIL_USERNAME (): null
- MAIL_ENCRYPTION (): null
- MAIL_PASSWORD:
> @php artisan migrate

In Connection.php line 664:

  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (usin
  g password: NO) (SQL: select * from information_schema.tables where table_s
  chema = homestead and table_name = migrations)


In PDOConnection.php line 31:

  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (usin
  g password: NO)


In PDOConnection.php line 27:

  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (usin
  g password: NO)


Script @php artisan migrate handling the post-create-project-cmd event returned with error code 1

**Comment by aimeos** [comment]
Your database credentials were wrong. Add a user to your database, check with the mysql client if you can log in and use those username/password pair during installation of Aimeos

**Comment by Alsaheem** [comment]
hello im just trying out aimeos and im still having the same issue in the sceenshot

**Comment by Alsaheem** [comment]
@aimeos 
ive migrated the database and only the user tables and the passwords reset  tables are there

The database credentials
![3](https://user-images.githubusercontent.com/38351524/63733435-46ba0800-c870-11e9-901c-3b158423625f.PNG)

The error on browser
![1](https://user-images.githubusercontent.com/38351524/63733436-47529e80-c870-11e9-8426-b5c8e8f847a4.PNG)

The installation
![2](https://user-images.githubusercontent.com/38351524/63733437-47529e80-c870-11e9-9903-bf0690d484a0.PNG)

**Comment by aimeos** [comment]
This repository is for the Aimeos shop application. If you install the Aimeos package for Laravel in your existing application, you have to use the step by step guide it its repository:
https://github.com/aimeos/aimeos-laravel#table-of-content

Your problem: You haven't run `php artisan aimeos:setup --option=setup/default/demo:1` like stated in the readme file

**Comment by Alsaheem** [comment]
thanks , it works now
i dont think i saw this command "php artisan aimeos:setup --option=setup/default/demo:1" in the readme tho
