### ISSUE TITLE
Mysql CA problem

### ISSUE THREAD

**Issue by fmarslan** [aimeos/aimeos#135]
Hi, I'm using Azure MySQL with SSL CA. I encountered the following exception during the setup process:

```plaintext
An exception occurred in the driver: SQLSTATE[HY000] [2002] (trying to connect via (null)): SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'
```

Upon inspecting the Laravel database connection settings, I noticed that the `PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT` row is missing on line 62 [here](https://github.com/aimeos/aimeos/blob/d1dc163821b9026b4b2bf87a4c90793737c66608/config/database.php#L62).

Adding the following row to line 62 resolves the issue:

```php
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('MYSQL_ATTR_SSL_VERIFY_SERVER_CERT'),
```

"I will create a PR if you want me to fix it.

Detailed Exception:

```sh
> php artisan aimeos:setup

   Aimeos\Base\DB\Exception 

   An exception occurred in the driver: SQLSTATE[HY000] [2002] (trying to connect via (null)): SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8mb4'; SET SESSION sql_mode='ANSI'

   at vendor\aimeos\aimeos-base\src\DB\Statement\DBAL\Simple.php:75
      71▕ {
      72▕     try {
      73▕         $result = $this->getConnection()->getRawObject()->getWrappedConnection()->query($this->sql);
      74▕     } catch (\Doctrine\DBAL\Driver\Exception $e) {
   ➜  75▕         throw new \Aimeos\Base\DB\Exception($e->getMessage() . ': ' . $this->sql, $e->getCode());
      76▕     }
      77▕
      78▕     return new \Aimeos\Base\DB\Result\DBAL($result);
      79▕ }
```

After adding the row:

``sh
> php artisan aimeos:setup
Initializing or updating the Aimeos database tables for site "default"
Migrating: \vendor\aimeos\aimeos-core\setup\TypesMigrateColumns.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TypesMigrateColumns.php (645.55ms)
Migrating: \vendor\aimeos\aimeos-core\setup\AttributeMigrateKey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\AttributeMigrateKey.php (0.23ms)
Migrating: \vendor\aimeos\aimeos-core\setup\TablesClearPropertyKey.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TablesClearPropertyKey.php (0.1ms)
Migrating: \vendor\aimeos\aimeos-core\setup\IndexMigrateTextInnodb.php
Migrated:  \vendor\aimeos\aimeos-core\setup\IndexMigrateTextInnodb.php (0.11ms)
Migrating: \vendor\aimeos\ai-laravel\setup\TablesMigrateSiteidLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\TablesMigrateSiteidLaravel.php (0.11ms)
Migrating: \vendor\aimeos\aimeos-core\setup\TablesMigrateSiteid.php
Migrated:  \vendor\aimeos\aimeos-core\setup\TablesMigrateSiteid.php (0.09ms)
Migrating: \vendor\aimeos\ai-laravel\setup\TypesMigrateColumnsLaravel.php
Migrated:  \vendor\aimeos\ai-laravel\setup\TypesMigrateColumnsLaravel.php (0.13ms)
Migrating: \vendor\aimeos\aimeos-core\setup\Attribute.php
Migrated:  \vendor\aimeos\aimeos-core\setup\Attribute.php (1447.65ms)
Migrating: \vendor\aimeos\aimeos-core\setup\AttributeRemoveIndexes.php

....

``

**Comment by aimeos** [comment]
Thank you very much! A PR would be great :-)
