### ISSUE TITLE
Custom theme for actual version 2024

### ISSUE THREAD

**Issue by ondrei** [aimeos/aimeos#139]
Hi,

may I ask for guidance on how to install a custom theme if I have the latest version of Aimeos, but the generator only allows me to use the 2023 version?

```
ondrei  ›  composer req aimeos-themes/emotions
./composer.json has been updated
Running composer update aimeos-themes/emotions
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires aimeos-themes/emotions * -> satisfiable by aimeos-themes/emotions[dev-master].
    - aimeos-themes/emotions dev-master requires aimeos/aimeos-laravel ^2023.04 -> found aimeos/aimeos-laravel[2023.04.1, ..., 2023.10.x-dev] but it conflicts with your root composer.json require (2024.04.*).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require aimeos-themes/emotions:*" to figure out if any version is installable, or "composer require aimeos-themes/emotions:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### SOLVED .)

packages/yourheme/composer.json:

```
	"require": {
		"php": "^8.1",
		"aimeos/aimeos-laravel": "2024.04.*"
	},
```

**Comment by aimeos** [comment]
There are a bit more changes included in the 2024.x packages which can now be generated by the extension builder. Please create a new 2024.x extension here: https://aimeos.org/extensions

**Comment by aimeos** [comment]
> Overall, thank you for this really great framework, and I look forward to its further development! I stumbled upon it by chance, and I can't praise its design and speed enough!

Thanks, we really like to hear that you love Aimeos as much as we do :-)

> Off-topic: The only thing I could use advice on... Is it possible to arrange a bulk photo import that creates individual products based on the photo name?

Sure, but you have to implement that yourself. The options would be to extend the admin backend or create an job controller for imports from the file system.
- https://aimeos.org/docs/latest/admin/jqadm/implement-panels/
- https://aimeos.org/docs/latest/cronjobs/create-job-controller/
