### ISSUE TITLE
Items disappearing from the basket preview bar

### ISSUE THREAD

**Issue by ondrei** [aimeos/aimeos#140]
Hello, 

I noticed an issue with the cart: When I add an item to the cart, click on checkout, "change my mind," and then go back, for example, to the homepage, the item disappears from the cart preview. However, when I click on the cart again, the item reappears. 

I'm attaching a video from Aimeos demo page: https://www.loom.com/share/d678ba003f364416a82423374e477f9b

On localhost, instead of the cart icon, I sometiomes get an error message: A non-recoverable error occured

**Comment by aimeos** [comment]
This is due to browser caching for performance reasons. The browser will cache the home page for 30 sec:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Controller/CatalogController.php#L86

**Comment by aimeos** [comment]
> Is there a way to disable the cache, or at least overwrite it?

You can change the `cache_maxage` value in the ./config/shop.php

> Also, I encountered another issue - the inability to pin from the catalog. The user has to click through to the detail view for it to work.

The demo doesn't use the 2024.04 version yet. There, it works without problems.

> Plus, after logging into Demo Admin, it redirects to a different page (in my case, to Google, where I came from). The user has to navigate to the admin page twice.

Strange, we can't reproduce that issue in the demo ourselves.

**Comment by aimeos** [comment]
Add `'cache_maxage' => 0,` here: https://github.com/aimeos/aimeos/blob/master/config/shop.php#L63

When using Google Chrome as browser, we don't see the same behavior like in your video. Is there any error in the browser console?
