### ISSUE TITLE
getting a base/db/exception?

### ISSUE THREAD

**Issue by abs9240** [aimeos/aimeos#141]
[v](http://intovus.cloud/myshop/public/)

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newintv.mshop_locale_site' doesn't exist: SELECT mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid", mlocsi."label" AS "locale.site.label", mlocsi."code" AS "locale.site.code", mlocsi."status" AS "locale.site.status", mlocsi."id" AS "locale.site.position", mlocsi."level" AS "locale.site.level", mlocsi."config" AS "locale.site.config", mlocsi."icon" AS "locale.site.icon", mlocsi."logo" AS "locale.site.logo", mlocsi."rating" AS "locale.site.rating", mlocsi."ratings" AS "locale.site.ratings", mlocsi."refid" AS "locale.site.refid", mlocsi."theme" AS "locale.site.theme", mlocsi."ctime" AS "locale.site.ctime", mlocsi."mtime" AS "locale.site.mtime", mlocsi."editor" AS "locale.site.editor", mlocsi."parentid" AS "locale.site.parentid" FROM "mshop_locale_site" mlocsi WHERE ( ( mlocsi."code" = 'default' ) ) ORDER BY mlocsi."id" ASC LIMIT 1 OFFSET 0

Upon installation, when trying to access, it shows page with above. I was told that the app didn't bother creating any tables within the db. what am i doing wrong as the installation process through ssh showed that it was created.

**Comment by aimeos** [comment]
The setup process didn't succeed and the tables haven't been created.
Any errors during the installation?

**Comment by abs9240** [comment]
Hi. I missed the instructions.

I got up to the point where I would try to create a super user account. When inputting in SSH, this is what shows.

[iad1-shared-b8-40]$ php artisan aimeos:account --super ***@***.******@***.***>
PHP Warning:  Invalid "memory_limit" setting. Invalid quantity "30--512M", interpreting as "30M" for backwards compatibility in Unknown on line 0
Cannot load Zend OPcache - it was already loaded

Password:
>


   Aimeos\Base\DB\Exception

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'newintv.mshop_locale_site' doesn't exist:
                                        SELECT mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid", mlocsi."label" AS "locale.site.label", mlocsi."code" AS "locale.site.code", mlocsi."status" AS "locale.site.status", mlocsi."id" AS "locale.site.position", mlocsi."level" AS "locale.site.level", mlocsi."config" AS "locale.site.config", mlocsi."icon" AS "locale.site.icon", mlocsi."logo" AS "locale.site.logo", mlocsi."rating" AS "locale.site.rating", mlocsi."ratings" AS "locale.site.ratings", mlocsi."refid" AS "locale.site.refid", mlocsi."theme" AS "locale.site.theme", mlocsi."ctime" AS "locale.site.ctime", mlocsi."mtime" AS "locale.site.mtime", mlocsi."editor" AS "locale.site.editor", mlocsi."parentid" AS "locale.site.parentid"
                                        FROM "mshop_locale_site" mlocsi
                                        WHERE ( ( mlocsi."code" = 'default' ) )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0

  at vendor/aimeos/aimeos-base/src/DB/Statement/DBAL/Simple.php:75
     71▕        {
     72▕                try {
     73▕                        $result = $this->getConnection()->getRawObject()->getWrappedConnection()->query( $this->sql );
     74▕                } catch( \Doctrine\DBAL\Driver\Exception $e ) {
  ➜  75▕                        throw new \Aimeos\Base\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
     76▕                }
     77▕
     78▕                return new \Aimeos\Base\DB\Result\DBAL( $result );
     79▕        }

      +30 vendor frames

  31  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by aimeos** [comment]
> Warning: Invalid "memory_limit" setting. Invalid quantity "30--512M", interpreting as "30M" for backwards compatibility 

This is your problem. There should be no memory limit for PHP on the command line or a high value of 1G.
After you've fixed that problem, reinstall the Aimeos distribution from scratch.

**Comment by abs9240** [comment]
Great! Thank you!


Sincerely,

Anthony Son

***@***.******@***.***>

This message, together with any attachments,is intended only for the use of the individual or entity to which it is addressed and may contain information that is legally privileged, confidential and exempt from disclosure. If you are not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this message, or any attachment, is strictly prohibited. If you have received this message in error, please notify the original sender immediately by return email and delete this message, along with any attachments, from your computer.



________________________________
