### ISSUE TITLE
HOW TO EDIT THE DEFAULT HOMEPAGE

### ISSUE THREAD

**Issue by bajwa4200** [aimeos/aimeos#143]
In admin inside CMS there is a demo homepage but it is not showing itself on "/" route the instructions in readme said to remove the default laraval installation homepage use this route "Route::group(['middleware' => ['web']], function () {
    Route::get('/', '\Aimeos\Shop\Controller\CatalogController@homeAction')->name('aimeos_home');
});" but the page this route is showing has a slider and a footer and megamenu only all the content of the Demo homepage from cms is not on the "/" route as set in the admin panel how to fix it ? and also where is the blade file for this "'aimeos_home" i cant seem to find it

**Comment by aimeos** [comment]
You can edit the content of the defautl home page here:
https://admin.demo.aimeos.org/admin/default/jqadm/get/cms/2?locale=en#content

The pages with CMS content use the base Blade template like all other Aimeos pages:
https://github.com/aimeos/aimeos-laravel/blob/master/views/base.blade.php

**Comment by bajwa4200** [comment]
![image](https://github.com/user-attachments/assets/b0a69248-2d1f-4ad9-acba-df06bd3487a8)
i can only see this in my home url

**Comment by bajwa4200** [comment]
and also there are only two active currencies EUR and USD for the website how to add more to that i tried enabling from here but it does not work i can only see two 
![image](https://github.com/user-attachments/assets/a70363f8-2451-417e-86f8-e1824efdf16f)
Even though these all are active i can see only two options in the header "USD", "EUR" how to make "PKR" the default currency not "EUR"

**Comment by bajwa4200** [comment]
And also can you tell me how to edit the header and footer

**Comment by aimeos** [comment]
> i can only see this in my home url

What is  the URL of the page? Did you change any routes? Did you change anything in the CMS module?

> Even though these all are active i can see only two options in the header "USD", "EUR" how to make "PKR" the default currency not "EUR"

Add the accepted language/currency combinations in the Locale panel

> And also can you tell me how to edit the header and footer

Overwrite the base.blade.php file: https://aimeos.org/docs/latest/laravel/extend/#aimeos-blade-templates

**Comment by bajwa4200** [comment]
What is the URL of the page? Did you change any routes? Did you change anything in the CMS module?

The url of the page is : Route::group(['middleware' => ['web']], function () {
    Route::get('/', '\Aimeos\Shop\Controller\CatalogController@homeAction')->name('aimeos_home');
});

In the local panel : 
All of the languages and currencies were enabled except pkr still i can only see ENGLISH and GERMAN as language options and EUR and USD as currencies option in my header
![image](https://github.com/user-attachments/assets/d1c9159b-fb62-450c-a9e0-8385b2ac22ad)
![image](https://github.com/user-attachments/assets/e0bd17a9-9189-46aa-b843-003adbc69043)

**Comment by bajwa4200** [comment]
And also i could not understand how to edit the base file the base file in my project at vendor/aimeos/aimeos-laravel/base.blade.php has yield('aimeos_body') but i dont see any body on my home page just the header and footer content  and sliders how can i bring "/" demo homepage to my actual homepage

**Comment by aimeos** [comment]
> In the local panel : All of the languages and currencies were enabled except pkr still i can only see ENGLISH and GERMAN as language options and EUR and USD as currencies option in my header

Add the accepted language/currency combinations in the Locale panel

> And also i could not understand how to edit the base file the base file in my project at vendor/aimeos/aimeos-laravel/base.blade.php has yield('aimeos_body') but i dont see any body on my home page just the header and footer content and sliders how can i bring "/" demo homepage to my actual homepage

https://aimeos.org/docs/latest/laravel/extend/#aimeos-blade-templates

The sections referenced in the base.blade.php are sourced from the Blade templates for the controller/actions:
https://github.com/aimeos/aimeos-laravel/tree/master/views

**Comment by bajwa4200** [comment]
Can you just give me the code for the demo home page to be rendered here 
![image](https://github.com/user-attachments/assets/7e48ad6f-773a-4e50-bee5-abe6c0b4a566)
this is the home page just give me the code for demo homepage at "/" to be rendered here

**Comment by aimeos** [comment]
This is the code that is added by the setup tasks if you run `php artisan aimeos:setup --option=setup/default/demo:1`:
https://github.com/aimeos/ai-cms-grapesjs/blob/master/setup/default/data/demo-cms.php#L14

**Comment by bajwa4200** [comment]
i know how to add components to the cms page please tell me how can i add the basket component to products in the cms page given below as they are in the shop/{category}
![image](https://github.com/user-attachments/assets/a731c86e-33c7-4a16-b6d7-76207c0bcc1d)
![image](https://github.com/user-attachments/assets/5b5a3dca-e542-4a79-9236-b08546383158)

**Comment by bajwa4200** [comment]
and also how to setup direct debit payment like how to setup online payment system i saw the docs and coudnt find anything i have my stripe public and private key but where should i put it for the payment to go through

**Comment by aimeos** [comment]
> i know how to add components to the cms page please tell me how can i add the basket component to products in the cms page given below as they are in the shop/{category}

Set `client/html/cms/page/basket-add` to `true` in your configuration:
https://aimeos.org/docs/latest/laravel/customize/

To configure Stripe as payment provider, please read here:
https://aimeos.org/docs/latest/manual/services/#stripe

**Comment by bajwa4200** [comment]
<?php

/**
 * @license LGPLv3, http://opensource.org/licenses/LGPL-3.0
 * @copyright Aimeos (aimeos.org), 2021-2023
 */


/** client/html/cms/page/basket-add
 * Display the "add to basket" button for each product item
 *
 * Enables the button for adding products to the basket for the products in CMS
 * pages. This works for all type of products, even for selection products
 * with product variants and product bundles. By default, also optional attributes
 * are displayed if they have been associated to a product.
 *
 * To fetch the variant articles of selection products too, add this setting to
 * your configuration:
 *
 * mshop/common/manager/maxdepth = 3
 *
 * @param boolean True to display the button, false to hide it
 * @since 2021.07
 * @see client/html/catalog/home/basket-add
 * @see client/html/catalog/lists/basket-add
 * @see client/html/catalog/detail/basket-add
 * @see client/html/catalog/product/basket-add
 * @see client/html/basket/related/basket-add
 */

$enc = $this->encoder();


?>
<div class="catalog-list swiffy-slider slider-nav-outside">
	<div class="catalog-list-items product-list slider-container">

		<?= $this->partial(
			$this->config( 'client/html/common/partials/products', 'common/partials/products' ),
			array(
				'require-stock' => (int) $this->config( 'client/html/basket/require-stock', true ),
				'basket-add' => $this->config( 'client/html/cms/page/basket-add', true ),
				'attributeTypes' => $this->get( 'attributeTypes', map() ),
				'products' => $this->get( 'products', map() ),
			)
		) ?>

	</div> i did it still cant see the basket 
![image](https://github.com/user-attachments/assets/7aedf613-d9da-46b7-b820-a955dc270019)

**Comment by aimeos** [comment]
Please show your configuration

**Comment by bajwa4200** [comment]
That problem was solved. 
i dont understand this i've ran the command this command "composer req aimeos/ai-payments omnipay/stripe" now what should i do to setup stripe as my payment method tell me step by step 
Stripe[#](https://aimeos.org/docs/latest/manual/services/#stripe)
The [Stripe](https://stripe.com/) payment gateway is available via the Stripe payment service provider. It supports credit card payments and authorization before capture. If you use composer run:


composer req aimeos/ai-payments omnipay/stripe
The available configuration options are:

apiKey (string, required)
The secret API key string from your Stripe account
publishableKey (string, requires)
Public key used in the JS frontend code to authenticate to Stripe
stripe.address (boolean, optional)
A value of "1" will send the customer address to the Stripe server for additional verification
stripe.authorize (boolean, optional)
Use "1" if you want to get an authorization first and capture the payment after the parcel has been dispatched or the product delivered according to the delivery status of the order. Leave this setting out for immediate payments
address (boolean, optional)
Not supported by that payment provider
authorize (boolean, optional)
Not supported by that payment provider
createtoken (boolean, optional)
Use "1" to enable token based payments for subscriptions
onsite (boolean, optional)
Must be "1" to enable customers to enter their payment details (credit card data) during the checkout process
testmode (boolean, optional)
Use "1" for test payments without real money
Warning

Stripe requires external Javascript and you need a customized [Content Security Policy](https://aimeos.org/docs/latest/laravel/setup/#content-security-policy):


<meta http-equiv="Content-Security-Policy" content="base-uri 'self'; default-src 'self' 'nonce-{{ ap

**Comment by aimeos** [comment]
Please create a new topic for every support question you have in the Aimeos forum because the Git issues are only for issues and bug related things: https://aimeos.org./help

**Comment by bajwa4200** [comment]
I've posted my query about stripe there kindly approve that and answer me
