### ISSUE TITLE
Post install script errors because currency is wrong

### ISSUE THREAD

**Issue by Fuzzyma** [aimeos/aimeos#144]
Running the "post-create-project-cmd" script throws this:

```sh
Migrating: vendor/aimeos/aimeos-core/setup/default/DemoAddOrderData.php

   Aimeos\MShop\Price\Exception

  Price can not be added. Currency ID "EUR" of price item and currently used currency ID "USD" does not match.

  at vendor/aimeos/aimeos-core/src/MShop/Price/Item/Standard.php:437
    433▕        {
    434▕                if( $item->getCurrencyId() != $this->getCurrencyId() )
    435▕                {
    436▕                        $msg = 'Price can not be added. Currency ID "%1$s" of price item and currently used currency ID "%2$s" does not match.';
  ➜ 437▕                        throw new \Aimeos\MShop\Price\Exception( sprintf( $msg, $item->getCurrencyId(), $this->getCurrencyId() ) );
    438▕                }
    439▕
    440▕                if( $this === $item ) { $item = clone $item; }
    441▕                $taxValue = $this->getTaxValue(); // use initial value before it gets reset

      +20 vendor frames

  21  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

Why does this happen? Can I change the default currency somehow so that it works?

**Comment by aimeos** [comment]
Thanks for your report! The problem has been fixed and a new version is available. Run `composer up` and `php artisan aimeos:setup --options=setup/default/demo:1` or reinstall from scratch.

**Comment by Fuzzyma** [comment]
Ok, seems like your main-readme doesnt have all information needed.
I used `composer create-project` and it didnt work out:
https://github.com/aimeos/aimeos?tab=readme-ov-file#installation

Or did you JUST fixed it?

**Comment by aimeos** [comment]
`composer create-project` will reinstall the a new project from scratch. With `composer up` and `php artisan aimeos:setup --option=setup/default/demo:1`, you can update an already existing installation

**Comment by Fuzzyma** [comment]
But I created the project yesterday. Did anything change since yesterday?

**Comment by aimeos** [comment]
Yes, the bug was fixed and a new version of aimeos/aimeos-core tagged
