### ISSUE TITLE
Error on registration

### ISSUE THREAD

**Issue by johnywind** [aimeos/aimeos#147]
On a fresh install of the standalone version after submitting the registration form we get this error:
**Locale item for site "X" not found**
The line that throws this error is located at app\Http\Controllers\Auth\RegisteredUserController.php: 99
`$context->setLocale( \Aimeos\MShop::create( $context, 'locale' )->bootstrap( $request->code ) );`

**Comment by johnywind** [comment]
I have `SHOP_REGISTRATION=true` in my .env file right now. I also tried `True `and `1`, with the same results.
The site data seems to be saved in the `mshop_locale_site` table but not in `mshop_locale`. Or maybe it should be saved in `mshop_locale` first?

**Comment by aimeos** [comment]
Yes, you are right. The locale item needs to be added to new sites too to be usable in SaaS setups. We will care about that

**Comment by aimeos** [comment]
Did you also enable `SHOP_MULTISHOP=true`? Your setup is a SaaS-like setup or a marketplace setup?

**Comment by johnywind** [comment]
yes, I did enable SHOP_MULTISHOP but this is a fresh install. My project would look, in the end, more like a SaaS than a Marketplace, but that's still a long way to go. Here's my` .env` variables:
`SHOP_MULTILOCALE=1
SHOP_MULTISHOP=1
SHOP_REGISTRATION=1
SHOP_PERMISSION=admin`

**Comment by johnywind** [comment]
I did a fresh install with 2024.07.x-dev and I can confirm that the locale has now been created when registrating. So this issue has been solved
However, the registration process throws an error in `RegisteredUserController.php: 42` ( `event(new Registered($user));` ):
`An email must have a "From" or a "Sender" header.`

**Comment by aimeos** [comment]
You have to set `MAIL_FROM_ADDRESS` in your `.env` file: https://github.com/aimeos/aimeos/blob/master/.env.example#L39

**Comment by johnywind** [comment]
Still something's not quite right. I get this error:
`Item with ID "8" in "customer.id"` not found
`from app\Http\Middleware\SetLocale.php: 25`

**Comment by aimeos** [comment]
It happened when your user for the new site switched to another site. Most likely, registration is done at the default site and Laravel redirects the user after registration back to that site while being bound to the new site. We've fixed that so no exception is thrown any more but new users won't have access to their profile on sites which are not their site.

Please run `composer up` to get the latest `aimeos/aimeos-laravel` package.

**Comment by johnywind** [comment]
We're getting closer :)
The registration process went through all the way (thanks for that).
However, when I try to login in as the newly created user I get the error `127.0.0.1 redirected you too many times.
Try deleting your cookies.
ERR_TOO_MANY_REDIRECTS`

**Comment by johnywind** [comment]
I figured it out. After registration, I have to assign the new user a role, such as editor. 
Anyway, some error handling would be useful there.

**Comment by aimeos** [comment]
By default, the admin user role is added to newly registered vendors:
https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L104-L116

Did you change something in the configuration regarding the assigned group, e.g. in the `.env` file?

**Comment by aimeos** [comment]
Can you check what happens here and why the group isn't assigned in your setup?
https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L104-L116

**Comment by johnywind** [comment]
As far as I can tell this line doesn't do anything: `$manager->save( $item );`
The value of `$item` is:
```
Aimeos\MShop\Common\Item\Lists\Standard {#10160 ▼ // app\Http\Controllers\Auth\RegisteredUserController.php:115
  #available: true
  #modified: true
  #bprefix: "customer.lists."
  #type: "customer/lists"
  #bdata: array:6 [▼
    "customer.lists.siteid" => "9."
    ".date" => "2024-09-30 10:17:36"
    "customer.lists.domain" => "group"
    "customer.lists.parentid" => "12"
    "customer.lists.type" => "default"
    "customer.lists.refid" => "18"
  ]
  -date: "2024-09-30 10:17:36"
  -prefix: "customer.lists."
  -refItem: null
}
```
This values should be saved into `mshop_customer_list` or `mshop_customer` tables, right?

**Comment by aimeos** [comment]
For Laravel, it must be stored in the `users_list` table and the dump of the item looks fine. Can you enable debug level logging (https://github.com/aimeos/aimeos-laravel/blob/master/config/shop.php#L171) and check in Log panel of the admin backend, if the SQL query for inserting the item is executed and if yes, what happens afterwards?

**Comment by johnywind** [comment]
the information seems correct in `users_list`:
![image](https://github.com/user-attachments/assets/e50c0d63-397a-4b5d-a88c-8b19f90d2a57)
and in the `group` table:
![image](https://github.com/user-attachments/assets/991b3eb9-7fe7-4398-849e-907d3b9bb405)

**Comment by aimeos** [comment]
And the login to the admin backend still doesn't work? You are using `/admin` for login? Make sure, you are not logged in with another user before you want to login with a new user because this causes the redirect loop you've mentioned. The already logged in user is from another site and doesn't have access to the groups of of the new site (and they are not assigned to the user from another site).

**Comment by johnywind** [comment]
Ok. I think I figured out the issue (not the fix).
When I register a new user, in `users_list` table the key saved for the group is `group|default|46` where 46 is the id of the **admin** group saved in the `mshop_group` for my newly created site (23 in my case).
When I log into the admin the url is redirecting to http://127.0.0.1:8000/en/default/login. So I'm assuming that when I login, the controller expects the key in `users_list` to be `group|default|1` since **1** is the id for the **admin** group for the site `default`.
That's why it works when I log in as a super-admin (that belongs to site with id 1) and assign the group admin to the user. This one it's still called admin, but has a different id.
Makes sense?

**Comment by johnywind** [comment]
I tried to enter that url manually but I get redirected to default

**Comment by aimeos** [comment]
After registration, the new vendors should be redirected to their sites:
https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L46-L47

Does that work?

**Comment by johnywind** [comment]
Yes, after registration the user is redirected to **/language/sitename** (http://127.0.0.1:8000/en/newsite in my case). 
But if, after that, I go directly to `http://127.0.0.1:8000/en/newsite/login` it redirects to `http://127.0.0.1:8000/admin` and I get **ERR_TOO_MANY_REDIRECTS**.

If I logout from the front homepage and afterwards go to _http://127.0.0.1:8000/en/newsite/login_ I input the new credentials and the form redirects to _http://127.0.0.1:8000/en/default/shop/count?count=tree_  which prints` {"1":1,"15":2,"2":2,"3":1}`

**Comment by aimeos** [comment]
> Yes, after registration the user is redirected to **/language/sitename** (http://127.0.0.1:8000/en/newsite in my case). But if, after that, I go directly to `http://127.0.0.1:8000/en/newsite/login` it redirects to `http://127.0.0.1:8000/admin` and I get **ERR_TOO_MANY_REDIRECTS**.

Your new vendor is already logged in after registration and the admin controller thinks it isn't in that code block because the the site seems to be the "default" instead of "newsite": https://github.com/aimeos/aimeos-laravel/blob/master/src/Controller/AdminController.php#L35-L39

The checks for the groups are done here:
- https://github.com/aimeos/aimeos/blob/master/app/Providers/AppServiceProvider.php#L68-L74
- https://github.com/aimeos/aimeos-laravel/blob/master/src/Base/Support.php#L56-L86

Can you check what `$site` is at the end any why?

> If I logout from the front homepage and afterwards go to _http://127.0.0.1:8000/en/newsite/login_ I input the new credentials and the form redirects to _http://127.0.0.1:8000/en/default/shop/count?count=tree_ which prints` {"1":1,"15":2,"2":2,"3":1}`

It seems, Laravel redirects you to the last URL stored in the session but the URL is an JSON API request.

**Comment by johnywind** [comment]
Indeed, when I create the new user, the **siteid** is **1** (default). 
Can that be because the registration URL is `http://127.0.0.1:8000/en/default/register` ?

**Comment by johnywind** [comment]
I investigated further and it looks like the reason `siteId` is 1 (default) is because the new site is not yet created when `siteid()` method is called.

Thinking further, I think a better approach would be to have two routes / methods:
- one for registering a new user 
- one for creating a new site and it's corresponding user / admin

**Comment by aimeos** [comment]
Sorry, we've introduced a bug in the last change and this is the fix:
https://github.com/aimeos/aimeos/commit/af5c381a613c5e48675513dfe34d93c5180a0e65

**Comment by johnywind** [comment]
I tried this fix but it solves the problem only partially. I can register the new user all the way and the **siteid** and **key** are saved correctly in `users_list`.
However, when I try to login with this user in the admin section, I get `ERR_TOO_MANY_REDIRECTS`

**Comment by aimeos** [comment]
Are the siteid values in the `users` and `mshop_group` table also the same like in `users_list`?
The last point is good because the user of the new vendor is now assigned to the correct site and you will see the user account now only if you switch to the correct site using the site selector in the menu.

**Comment by johnywind** [comment]
All id's seem to be right in the three tables. 
I cannot see the new user when I switch to newly created site.
The redirect after the registration complete was `/en/newsite`.
When I log into `/en/newsite/login`, all the fields in billing and delivery address are empty. If I input some data into the address fields, a new user is created and this one I can see in the admin panel.

**Comment by aimeos** [comment]
Can you show with video what exactly your are doing?

**Comment by johnywind** [comment]
I recorded my usual process here: https://www.youtube.com/watch?v=H9dmQvAkbuI

**Comment by aimeos** [comment]
Thank you for the video! It seems that the `siteid` value in the `users` table is wrong because it must be `32.` instead of `32` (dot is missing). This line is still wrong: https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L81

Can you change it to `$siteId = $site->getSiteId();` instead?

**Comment by johnywind** [comment]
Alright... now the whole process works as it should. Thank you for the help.
I do have one question though: when creating a new site, how do I add a new group, let's say "customers"? Right now, when I use the register function I only have two options: "admin" and  "editor"

**Comment by aimeos** [comment]
Great! You can add a second group here too:
https://github.com/aimeos/aimeos/blob/master/app/Http/Controllers/Auth/RegisteredUserController.php#L110-L111

**Comment by johnywind** [comment]
If I use something other than Admin or Editor I get No item found for conditions: Array ( [group.code] => customer ) which makes sense. I was wondering if there's a more standard way of doing it (like a config), other than manually creating the group code after this line: https://github.com/aimeos/aimeos/blob/3574d90703c276f31d3f0aa4df94b9a1d7a0050c/app/Http/Controllers/Auth/RegisteredUserController.php#L106
