### ISSUE TITLE
constraints on users table fail on fresh installation

### ISSUE THREAD

**Issue by simonecosci** [aimeos/aimeos#15]
Probably a duplicate of 
https://github.com/aimeos/aimeos-laravel/issues/252
but seems still unsolved
Laravel make:auth command ships a simple migration to create the user's table but by default it's created using MyISAM engine.
this causes the following error

`aimeos SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`

I've added this line in database/migrations/2014_10_12_000000_create_users_table.php

Schema::create('users', function (Blueprint $table) {
	    **$table->engine = 'InnoDB';**
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });

I know it's not the right way maybe it should be done during 
\App\Composer::setup() call

Thank you
S.

**Comment by aimeos** [comment]
Thank you for your hint! Seems like your MySQL version doesn't create InnoDB tables by default. We've added your line to the migration script and to the ./config/database.php file :-)

Can you check by running one of these on your server:
- `composer create-project aimeos/aimeos:dev-master myshop`
- `composer create-project aimeos/aimeos:2018.10.x-dev myshop`

**Comment by simonecosci** [comment]
Works great !
nice :) 
ty
