### ISSUE TITLE
A non-recoverable error occured

### ISSUE THREAD

**Issue by Keerthi001** [aimeos/aimeos#16]
After completely installing the Aimeos shop application with composer , it showing A non-recoverable error occured in the browser. Please suggest about this. Thank you

**Comment by aimeos** [comment]
Can you post a screenshot and the corresponding entries in the madmin_log table?

**Comment by Keerthi001** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/40263113/60699199-7e5fa000-9f10-11e9-8079-01c42f25afb6.png)

**Comment by Keerthi001** [comment]
After downloading zip file from github, I have installed composer in that directory, later I have generated key after that I have run that in localhost, it shows the error like this SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aime1.mshop_locale_site' doesn't exist. Please find below is the screen shot for respective error.
![Screenshot (28)](https://user-images.githubusercontent.com/40263113/60699343-0e054e80-9f11-11e9-9338-34b240e2b9d8.png)

**Comment by aimeos** [comment]
Downloading the .zip file from Github doesn't work as expected. You have to download the `composer` file and run `composer create-project aimeos/aimeos myshop` afterwards
