### ISSUE TITLE
Themes link broken

### ISSUE THREAD

**Issue by OpeOnikute** [aimeos/aimeos#18]
I'm trying to learn how to customize the default theme, and on clicking [client/html/themes](https://github.com/aimeos/aimeos-core/tree/master/client/html/themes) on the [themes fundamental page](https://aimeos.org/docs/Developers/Themes/Theme_fundamentals), I got a 404 not found. Please where can I find this directory?

**Comment by aimeos** [comment]
Thank you for the hint!
The themes folder is now in the ai-client-html package (https://github.com/aimeos/ai-client-html/tree/master/client/html/themes) and the link in the docs is fixed.
