### ISSUE TITLE
Custom product URL don't work for all languages

### ISSUE THREAD

**Issue by FlorianMoser** [aimeos/aimeos#19]
When adding a custom URL slug to a product for all languages, the shop doesn't find the product.

How to reproduce:

1. Fresh shop installation. Make sure, there are multiple languages activated.
2. Create a new product named "My Product". The product appears on the list of products in the frontend and links to `/My_Product`(correct)
3. Edit the product, go to "Text" and add a new "URL segment", select "All" for language and enter "new-name" as value. On the lists of products in the frontend, the product now links to `/new-name`(still correct, that's what is expected)
4. Click this product to view the product detail page. Now there is an error: `Product "new-name" not found`

By manually entering the URL `/My_Product`, the product can still be accessed.

I noticed, that the DB contains by default a URL for each language of the product. Adding the "URL segment" text adds just a row with an empty language ID to the DB.

By specifying a "URL segment" for each language, the problem is solved. It's just the "All" option that doesn't work. It seems like there is a priority problem, when fetching the data from the DB.

**Comment by FlorianMoser** [comment]
A correction: specifying a "URL segment" for each language does work, but only for some languages. I have three languages (de/fr/en) and created a "URL segment" for each of them for "My Product", but only the "de" language works. fr/en still shows a `Product "new-name" not found`error.

**Comment by aimeos** [comment]
What are the records for each language in the mshop_index_text table?
Can you check what happens here in your case:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L681-L736

**Comment by FlorianMoser** [comment]
That's how the table looks after adding "URL segment" for "All" languages (product not found for all languages):

![aimeos_table_2](https://user-images.githubusercontent.com/8578668/65722510-aa706480-e0ac-11e9-9f60-7541a47e3527.jpg)

When I change the "URL segment" from "All" language to "German" (product found on german page, but not on others), the table looks like this:

![aimeos_table_3](https://user-images.githubusercontent.com/8578668/65722515-acd2be80-e0ac-11e9-854e-99f6dabd96ab.jpg)

When I then add the "URL segment" for french and english, nothing changes. The table still looks like on the last picture, and product only shows on german page.

> Can you check what happens here in your case:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L681-L736

I'm not very familiar with Aimeos' architecture yet, but I will look into it tomorrow. Anything specific I should look for?

**Comment by aimeos** [comment]
It might be enough to extend that SQL conditions by
`mindte."langid" = $1 OR mindte."langid" IS NULL`
in https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L37

**Comment by FlorianMoser** [comment]
> It might be enough to extend that SQL conditions by
mindte."langid" = $1 OR mindte."langid" IS NULL

After I changed the query, always the first product is shown on the details page. So no luck here.

I investigated further. The problem is, how the URLs are saved. If I create a URL segment for every language, the DB contains exactly the same result, as you see in my second screenshot above. The row with langid=de shows "new-name" as URL. The other languages still have "My_Product" as url.

Changing them manually to "new-name", works. It seems there are two problems:

1. By saving a product with custom URL segments (one for every language), only one segment for one language is saved
2. Adding a URL segment for "All" languages creates a new row, instead of updating each row for each language (but doing so manually in the DB circumvents the problem)

The bug is where the segments are stored, not where the product is fetched.

**Comment by aimeos** [comment]
Did you add parenthesis around?
```( mindte."langid" = $1 OR mindte."langid" IS NULL )```

1.) Can you check again what happens here why only a segment for one language is stored:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L681-L736

2.) That's true. We will implement a way to fix that by removing the old entries afterwards

**Comment by FlorianMoser** [comment]
> Did you add parenthesis around?
( mindte."langid" = $1 OR mindte."langid" IS NULL )

I changed this to `( mindte."langid" = $1 OR mindte."langid" = \'\' )` (because langid is an empty string, not null), which works.

> 1.) Can you check again what happens here why only a segment for one language is stored:
https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Index/Manager/Text/Standard.php#L681-L736

The problem is, that `$item->getRefItems( 'text', 'url', 'default' )` only returns the german (default) language item. I traced it back to https://github.com/aimeos/aimeos-core/blob/master/lib/mshoplib/src/MShop/Common/Item/ListRef/Traits.php#L268

There, `$refItem->isAvailable()` returns false, when the langid is not "de".

**Comment by aimeos** [comment]
OK, but `langid` should be `null`, so we added that condition: https://github.com/aimeos/aimeos-core/commit/3bbc0f70d
Together with this commit, the products should now be found: https://github.com/aimeos/aimeos-core/commit/1ebb7826f4279f816d7de6acc94e99e080f15b01

`getRefItems()` behaves that way because a language ID is set in the context when storing the product in the admin interface. This should fix the problem: https://github.com/aimeos/aimeos-laravel/commit/c40d55c

**Comment by FlorianMoser** [comment]
Perfect, that fixed both situations explained above. Thank you.

In which release will those changes be available?

**Comment by aimeos** [comment]
The changes will be available in the upcoming 2019.10 releases (ETA: this month)

**Comment by aimeos** [comment]
The approach has some flaws, e.g. a new record is created for generic texts (url, name, etc.) but in combination with a full text search the products won't be found.

We use another way now: https://github.com/aimeos/aimeos-core/commit/06711e977160eb9aa59909de6778744e431e4dae

**Comment by aimeos** [comment]
Old records are now removed too: https://github.com/aimeos/aimeos-core/commit/859578903112a283a20514b4991fe391ab03c67a
