### ISSUE TITLE
can not create project 

### ISSUE THREAD

**Issue by XKangs** [aimeos/aimeos#2]
`D:\xampp\htdocs>composer create-project aimeos/aimeos myshop
Installing aimeos/aimeos (2017.10.1)
  - Installing aimeos/aimeos (2017.10.1): Loading from cache
Created project in myshop
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> mkdir public/files public/preview public/uploads
The syntax of the command is incorrect.
Script mkdir public/files public/preview public/uploads handling the post-root-p
ackage-install event returned with error code 1`

**Comment by aimeos** [comment]
Can you please try the dev-master version if that works?
```
composer create-project -s dev aimeos/aimeos
```

**Comment by aimeos** [comment]
Fixed and released a new version
