### ISSUE TITLE
Navbar issue (Even with updated app.blade.php)

### ISSUE THREAD

**Issue by vaulient** [aimeos/aimeos#22]
I've been installing and reinstalling aimeos trying to figure out as to why the navbar on my local does not look anything like the navbar on the demo website. My navigation is just a small little button next to the Aimeos title. I have attached a screenshot to preview the issue. Thank you in advance

![Screenshot_68](https://user-images.githubusercontent.com/57391221/68192473-554d3a00-ffec-11e9-971f-4125311d4957.png)

**Comment by aimeos** [comment]
The Laravel application template was for Boostrap 3, not 4. Now it's up to date, can you please try again?

**Comment by vaulient** [comment]
Fantastic! It works :) Thank you for the fast response, I appreciate it!


![Screenshot_1](https://user-images.githubusercontent.com/57391221/68216147-69f4f680-001b-11ea-87fc-b03f15cde5c5.png)

**Comment by aimeos** [comment]
If you replace the `./public/css/app.css` file with the new one, it will even look nicer :-)
https://github.com/aimeos/aimeos/blob/master/public/css/app.css
