### ISSUE TITLE
 Aimeos\MW\DB\Exception  DB related Issues!

### ISSUE THREAD

**Issue by lampsoft** [aimeos/aimeos#23]
When I run  php artisan aimeos:setup --option=setup/default/demo:1
I'm getting error, I check the mysql db and use 
'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_bin',
AND I follow the process/step giving in https://github.com/aimeos/aimeos-laravel
How can I resolve this DB issue?

> $ php artisan aimeos:setup --option=setup/default/demo:1
Initializing or updating the Aimeos database tables for site "default"
Add new type columns
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_attribute_property":                          OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_customer_property":                           OK
  Checking table "mshop_media":                                       OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_media_property":                              OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price":                                       OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product":                                     OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_property":                            OK
  Checking table "mshop_service":                                     OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_stock":                                       OK
  Checking table "mshop_supplier_list":                               OK
  Checking table "mshop_tag":                                         OK
  Checking table "mshop_text":                                        OK
  Checking table "mshop_text_list":                                   OK
Drop old unique indexes
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_attribute_property":                          OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_customer_property":                           OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_media_property":                              OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_property":                            OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_stock":                                       OK
  Checking table "mshop_supplier_list":                               OK
  Checking table "mshop_tag":                                         OK
  Checking table "mshop_text_list":                                   OK
Migrate typeid to type
  Checking table "mshop_attribute":                                   OK
  Checking table "mshop_attribute_list":                              OK
  Checking table "mshop_attribute_property":                          OK
  Checking table "mshop_catalog_list":                                OK
  Checking table "mshop_customer_list":                               OK
  Checking table "mshop_customer_property":                           OK
  Checking table "mshop_media":                                       OK
  Checking table "mshop_media_list":                                  OK
  Checking table "mshop_media_property":                              OK
  Checking table "mshop_plugin":                                      OK
  Checking table "mshop_price":                                       OK
  Checking table "mshop_price_list":                                  OK
  Checking table "mshop_product":                                     OK
  Checking table "mshop_product_list":                                OK
  Checking table "mshop_product_property":                            OK
  Checking table "mshop_service":                                     OK
  Checking table "mshop_service_list":                                OK
  Checking table "mshop_stock":                                       OK
  Checking table "mshop_supplier_list":                               OK
  Checking table "mshop_tag":                                         OK
  Checking table "mshop_text":                                        OK
  Checking table "mshop_text_list":                                   OK
Update attribute "key" columns
  Checking table mshop_attribute                                      OK
Renaming catalog index tables to index
  Checking table "mshop_catalog_index_attribute"                      OK
  Checking table "mshop_catalog_index_catalog"                        OK
  Checking table "mshop_catalog_index_price"                          OK
  Checking table "mshop_catalog_index_text"                           OK
Migrating configuration keys in coupon tables                         OK
Migrate mshop_index_text table engine to InnoDB                       OK
Prepare mshop_index_price table for simplification                    OK
Prepare mshop_index_text table for simplification                     OK
Remove mshop_locale char constraints
  Checking constraint for "langid"                                    OK
  Checking constraint for "currencyid"                                OK
Adding warehouse code to order base product table                     OK
Adding tax column to order tables
  Checking table "mshop_order_base_product":                          OK
  Checking table "mshop_order_base_service":                          OK
  Checking table "mshop_order_base":                                  OK
Rename "prodid" to "parentid" in table "mshop_product_stock"
  Checking column "prodid"                                            OK
Migrating product property domain to "product"                        OK
Changing warehouseid column in mshop_product_stock                    OK
Rename warehouse table
  Drop "mshop_product_stock.fk_msprost_whid"                          OK
  Drop "mshop_product_stock.fk_msprost_stock_warehouseid"             OK
  Rename "mshop_product_stock.wareshouseid"                           OK
  Rename "mshop_product_stock_wareshouse"                             OK
Move stock tables to own domain
  Checking "mshop_product_stock"                                      OK
  Checking "mshop_product_stock_type"                                 OK
Ensure unique codes in mshop_service                                  OK
Migrate product code in stock table
Clear property "key" columns
  Checking table mshop_attribute_property                             OK
  Checking table mshop_customer_property                              OK
  Checking table mshop_media_property                                 OK
  Checking table mshop_price_property                                 OK
  Checking table mshop_product_property                               OK
Update "siteid" columns
Moving product tag tables to own domain
  Moving table "mshop_product_tag_type"                               OK
  Moving table "mshop_product_tag"                                    OK
Rename "refid" to "parentid" in table "users_address"
  Checking column "refid"                                             OK
Remove left over Laravel user references
  Remove records from users_address                                   OK
  Remove records from users_list                                      OK
  Remove records from users_property                                  OK
Update Laravel "siteid" columns
Add new type columns for Laravel
  Checking table "users_list":                                        OK
  Checking table "users_property":                                    OK
Drop old unique indexes for Laravel
  Checking table "users_list":                                        OK
  Checking table "users_property":                                    OK
Migrate typeid to type for Laravel
  Checking table "users_list":                                        OK
  Checking table "users_property":                                    OK
Creating base tables
  Using schema from locale.php
    Checking table "mshop_locale_currency":                           done
    Checking table "mshop_locale_language":                           done
    Checking table "mshop_locale_site":
   Aimeos\MW\DB\Exception  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length
is 767 bytes: CREATE TABLE mshop_locale_site (id INT AUTO_INCREMENT NOT NULL, parentid INT DEFAULT NULL, siteid VARCHAR(255) NOT
 NULL, code VARCHAR(255) NOT NULL, `label` VARCHAR(255) NOT NULL, config TEXT NOT NULL, level SMALLINT NOT NULL, nleft INT NOT N
ULL, nright INT NOT NULL, status SMALLINT NOT NULL, mtime DATETIME NOT NULL, ctime DATETIME NOT NULL, editor VARCHAR(255) NOT NU
LL, UNIQUE INDEX unq_mslocsi_code (code), UNIQUE INDEX unq_mslocsi_siteid (siteid), INDEX idx_mslocsi_nlt_nrt_lvl_pid (nleft, nr
ight, level, parentid), INDEX idx_mslocsi_level_status (level, status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `
utf8mb4_bin` ENGINE = InnoDB

  at C:\xampp\htdocs\SCALA1\myshop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
  > 75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      C:\xampp\htdocs\SCALA1\myshop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\Setup\Task\Base.php:164

  2   Aimeos\MW\Setup\Task\Base::executeList("db-locale")
      C:\xampp\htdocs\SCALA1\myshop\vendor\aimeos\aimeos-core\lib\mshoplib\setup\TablesCreateMShop.php:173

  Please use the argument -v to see more details.

**Comment by aimeos** [comment]
You are using MySQL < 5.7.8 which doesn't support long indexes. Either use a MySQL 5.7+ database or install Laravel and Aimeos by hand and use `utf8`/`utf8_bin` as charset/collation.

Install Laravel by hand:
composer create-project laravel/laravel myshop

Documentation for installing Aimeos is here (incl. the hint for MySQL 5.6 charset/collation):
https://github.com/aimeos/aimeos-laravel#shop-package-only

**Comment by lampsoft** [comment]
Thank you for your quick respond.
The SHOP it is work now. But when I tried to go the BackEnd is yet to work. I'm getting Error 404.

**Comment by aimeos** [comment]
Did you install dev-master by accident?

**Comment by lampsoft** [comment]
Yes.
This has now been resolved.
Thanks
