### ISSUE TITLE
How to contribute to docs in the website

### ISSUE THREAD

**Issue by jbaron-mx** [aimeos/aimeos#24]
Hey, I've been digging the docs in the website ([link](https://aimeos.org/docs/Home)) and some parts need to be updated.

Are the docs somewhere here in Github so we can contribute to it?
I might also be able to translate it into Spanish.

**Comment by aimeos** [comment]
We are planning to move the Wiki content to Github this summer. It would be great if you can update the parts that our out of date so we already move the right content. Please write an e-mail to aimeos@aimeos.org asking for Wiki access.

A few people translated the documentation or parts thereof to other languages in the past but didn't care about it afterwards so the translations got quickly out of date. Thus, we want to stay with English docs only in the future.

**Comment by aimeos** [comment]
The new Aimeos documentation in Github is available here:
https://github.com/aimeos/aimeos-docs
