### ISSUE TITLE
Class "\Aimeos\MShop\Index\Manager\PgSQL" not available

### ISSUE THREAD

**Issue by albertguedes** [aimeos/aimeos#25]
I am trying install aimeos with postgresql database, and after solved LOTS of problems that occurs when we use other database that isnot mysql, this message is showed on home page

`Class "\Aimeos\MShop\Index\Manager\PgSQL" not available`

How to fix this? Whats is missing?

**Comment by aimeos** [comment]
What problems did you have using PostgreSQL? We check every commit for compatibility to MySQL, PostgreSQL and SQL Server. How can we improve compatibility further?

The `\Aimeos\MShop\Index\Manager\PgSQL` class doesn't exist any more and the right config is:
```
'mshop' => array(
    'index' => array(
        'manager' => array(
            'attribute' => array(
                'name' => 'Standard',
            ),
            'catalog' => array(
                'name' => 'Standard',
            ),
            'price' => array(
                'name' => 'Standard',
            ),
            'supplier' => array(
                'name' => 'Standard',
            ),
            'text' => array(
                'name' => 'PgSQL',
            ),
        ),
    ),
),
```
We've also updated the docs now: https://aimeos.org/docs/Developers/Library/Database_support
