### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by 1SA1** [aimeos/aimeos#28]
After registration of user its says that page not found error 404

**Comment by aimeos** [comment]
The Laravel Auth controllers redirect to `/home` by default which may not be available. If you execute 
```
composer req aimeos/aimeos:2019.10.x
```
or install again using
```
composer create-project aimeos/aimeos:2019.10.x myshop
```
you should get the latest version which redirects to the Aimeos "MyAccount" page.
Can you confirm that the problem is fixed in that version?

**Comment by 1SA1** [comment]
same issue everything is working fine when i register its says that page not found error 404 but when i change url manually i.e localhost:8000/shop it redicits with registered account. the only problem is after successful registration it do not redicts back to home page

**Comment by aimeos** [comment]
OK, you can't run `composer update` because it doesn't update the base project after installation any more.
Instead, you can either reinstall Aimeos using:
```
composer create-project aimeos/aimeos:2019.10.x myshop
```
or you can apply these changes to your installation: https://github.com/aimeos/aimeos/commit/b894e7d41e36ada8e722d22a0ba12f1dee15062a

**Comment by 1SA1** [comment]
Thanks lot bro now its working perfectly fine
