### ISSUE TITLE
I am trying to login to your forum site but to no avail.

### ISSUE THREAD

**Issue by adetheprince** [aimeos/aimeos#29]
I have tried to login with Github, Google but I get this message and no email sent.
I also checked on the spam folder but nothing has arrived. is this normal? I have tried to register but getting email, username already taken.

Information
The account has been created. However, the forum settings require account activation.
An activation key has been sent to your email address.

Return to the index page

I would like to ask you how to modify my Home page or add more pages in Aimoes, I have downloaded and installed without a problem, its working fine with no issue,  I have searched on your site for how to but I am really confused about your documentation due to different version I have I am guessing, I even dont know if this is Laravel or symfony but I have used the normal installation with composer (composer create-project aimeos/aimeos myshop), almost every documentation keep mention a file or folder that I dont have like client/html/ I am totally new to this script laravel and symfony, I need an example how to create menu or add nee page. My site works fine but I am stack with the default demo, I would really appreciate if you can show me a tutorial with the version I have installed or at least which file need to be edit for the frontend top menu and adding category, there are no other category than Home category, menu I meant  example like https://ashton-web.fr.

**Comment by aimeos** [comment]
> I have tried to login with Github, Google but I get this message and no email sent.
> I also checked on the spam folder but nothing has arrived. is this normal? I have tried to register but getting email, username already taken.

Our hoster informed us today that they deactivated sending e-mails due to Spam suspicion. We are currently investigating that together with the hoster. Please stay tuned, we inform you about any news.

**Comment by aimeos** [comment]
The registration is working again and you should have received the e-mail now.

The Aimeos distribution is based on Laravel and you should start here:
https://aimeos.org/docs/Laravel
