### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by R3ll36** [aimeos/aimeos#32]
`
In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
  ation_schema.tables where table_schema = myshop_db and table_name = migrati  
  ons)                                                                         
                                                                               

In PDOConnection.php line 31:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 27:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

Script @php artisan migrate handling the post-create-project-cmd event returned with error code 1`

**Comment by aimeos** [comment]
Which MySQL version are you using?
It seems your version doesn't support the information_schema tables

**Comment by aimeos** [comment]
Do you see the Information Schema tables in phpmyadmin?

**Comment by aimeos** [comment]
Maybe your user doesn't have permission to access the information_schema tables?
https://bugs.mysql.com/bug.php?id=86464
