### ISSUE TITLE
Interesting package

### ISSUE THREAD

**Issue by simplenotezy** [aimeos/aimeos#33]
How does people go about handling shipping with this package? I have brand new fresh eyes, and I am missing some documentation on shipping.

**Comment by aimeos** [comment]
Please have a look here:
https://aimeos.org/docs/2020.x/manual/services/

If you want to directly connect to DHL, UPS, etc. you have to implement an adapter for the service provider interface:
https://aimeos.org/docs/2020.x/providers/service/
