### ISSUE TITLE
how can solve?

### ISSUE THREAD

**Issue by stanley0212** [aimeos/aimeos#34]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.mshop_locale_site' doesn't exist: SELECT DISTINCT mlocsi."id" AS "locale.site.id", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" AS mlocsi WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' ) ORDER BY mlocsi."id" ASC LIMIT 1 OFFSET 0

**Comment by aimeos** [comment]
The database tables have not been created. Please run
```
php artisan aimeos:setup --option=setup/default/demo:1
```
