### ISSUE TITLE
Install exception due to https://api.github.com/graphql rate limiting

### ISSUE THREAD

**Issue by godadada** [aimeos/aimeos#35]
/   |  (_)___ ___  ___  ____  _____
  / /| | / / __ __  \/ _ \/ __ \/ ___/
 / __  |/ / / / / / / ___/ /_/ /\__ \
/_/  |_/_/_/ /_/ /_/\___/\____/_____/

Congratulations! You successfully set up your Aimeos shop!

Video tutorials: https://www.youtube.com/c/aimeos
Documentation: https://aimeos.org/docs
Get help: https://aimeos.org/help
Contribute: https://github.com/aimeos

Made with love by the Aimeos community. Be a part of it!

Script App\Composer::success handling the post-create-project-cmd event terminated with an exception

                                                                                 
  [Composer\Downloader\TransportException]                                       
  The "https://api.github.com/graphql" file could not be downloaded: failed to   
  open stream: Connection refused

**Comment by aimeos** [comment]
Seems like there was a problem with Github at the time of your installation.
Nevertheless, your installation may work. If not, try to install it again from scratch.
