### ISSUE TITLE
NOT migrating on my phone And not working on laptop

### ISSUE THREAD

**Issue by JESUDAWN** [aimeos/aimeos#36]
After installing I filled my details but failed to migrate.
I then use PHP artisan migrate, only about 4tables migrated.
I open on browser, it showing code error as seen in the image attached

![Screenshot_20201018-221836](https://user-images.githubusercontent.com/67759019/96386258-5772bf00-1191-11eb-9d4c-9e40268ebcfe.png)

**Comment by aimeos** [comment]
It seems that these tasks haven't been executed: https://github.com/aimeos/aimeos/blob/master/composer.json#L65-L67
Can you please redo your installation?

**Comment by JESUDAWN** [comment]
Reinstalled and working now. Thanks and my LORD JESUS CHRIST Bless

**Comment by JESUDAWN** [comment]
Is there dropshipping for bulit for aimeos just as for bagisto? If so
please help with the link.

**Comment by aimeos** [comment]
There's an extension from the Aimeos company offering the drop shipping feature:
https://aimeos.org/laravel-marketplace-ecommerce
