### ISSUE TITLE
Add stock level increment and decrement fields in product admin

### ISSUE THREAD

**Issue by brensondevalfa** [aimeos/aimeos#40]
If admin increases or decreases stock level it is possible to encounter race condition. 
Possible fix: add increment and decrement fields and than update stock level using those fields. Make stock level field red only and allow to enter it only when creating new product.

**Comment by aimeos** [comment]
Yes, that would be a good solution. Can you create a PR with the necessary changes for the JQAdm backend? The stock manager already has increase/decrease() methods.

**Comment by aimeos** [comment]
Implemented by this commit: https://github.com/aimeos/ai-admin-jqadm/commit/acf2973614ebdb5cd74db87a245a083be85384e4
