### ISSUE TITLE
change http:// to https://

### ISSUE THREAD

**Issue by xerc** [aimeos/aimeos#42]
MAIN
6 https://github.com/aimeos/aimeos/blob/master/README.md
1 https://github.com/aimeos/aimeos/blob/master/app/Composer.php
2 https://github.com/aimeos/aimeos/blob/master/resources/views/app.blade.php
BONUS
1 https://github.com/aimeos/aimeos/blob/master/public/packages/aimeos/shop/themes/elegance/email.css
2 https://github.com/aimeos/aimeos/blob/master/public/packages/aimeos/shop/themes/elegance/aimeos.js
2 https://github.com/aimeos/aimeos/blob/master/public/packages/aimeos/shop/themes/elegance/aimeos.css

**Comment by aimeos** [comment]
Can you create a PR with the changes?

**Comment by xerc** [comment]
already did
https://github.com/aimeos/aimeos-core/issues/202
but changes where overwritten
https://github.com/aimeos/aimeos/commit/9178a44001178f260b205b0335182e49ccf187ed#diff-4a9bf228fe32c7c7293fa4331208b4b17120a7fadb64e3b4cd51d3d60b35b5a3

**Comment by aimeos** [comment]
OK, changed the logo to HTTPS again. Thanks

**Comment by xerc** [comment]
it is also about the (ex. demo-) links to your domain

**Comment by aimeos** [comment]
Has been changed where applicable
