### ISSUE TITLE
Update to 2021.04

### ISSUE THREAD

**Issue by sm2x** [aimeos/aimeos#47]
Congratulations, when are you planning to upgrade (full shop) to 2021.04

**Comment by aimeos** [comment]
Thanks, the distribution will be available in 1-2 weeks as 2021.04

**Comment by sm2x** [comment]
I believe there will be an upgrade path from 2020.x to 2021.04?

**Comment by aimeos** [comment]
Yes, will be pretty easy

**Comment by aimeos** [comment]
2021.04 is now available
