### ISSUE TITLE
On creating new project

### ISSUE THREAD

**Issue by alifhs** [aimeos/aimeos#48]
Problem 1
    - aimeos/aimeos-laravel[2020.10.1, ..., 2020.10.x-dev] require aimeos/aimeos-core 2020.10.* -> satisfiable by aimeos/aimeos-core[2020.10.1, ..., 2020.10.x-dev].
    - aimeos/aimeos-core[2020.10.15, ..., 2020.10.x-dev] require php ~7.1||^8.0.1 -> your php version (8.0.0) does not satisfy that requirement.
    - aimeos/aimeos-core[2020.10.1, ..., 2020.10.14] require php ~7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires aimeos/aimeos-laravel ~2020.10 -> satisfiable by aimeos/aimeos-laravel[2020.10.1, ..., 2020.10.x-dev].

**Comment by aimeos** [comment]
PHP 8.0.0 is buggy and not supported but even newer PHP 8 versions are not fully stable. Up to now the savest option is to use PHP 7.4 until the bugs in PHP 8 are fixed.
