### ISSUE TITLE
missing table

### ISSUE THREAD

**Issue by waleedakram** [aimeos/aimeos#5]
An exception occurred while executing ' SELECT mlocsi."id" AS "locale.site.id", mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label", mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status", mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime", mlocsi."ctime" AS "locale.site.ctime" FROM "mshop_locale_site" AS mlocsi WHERE mlocsi."level" = 0 AND mlocsi."code" = 'default' GROUP BY mlocsi."id", mlocsi."code", mlocsi."label", mlocsi."config", mlocsi."status", mlocsi."editor", mlocsi."mtime", mlocsi."ctime" ORDER BY mlocsi."id" ASC LIMIT 100 OFFSET 0 ': SQLSTATE[42S02]
missing this table

**Comment by aimeos** [comment]
Have there been any error during the setup process?
Which environment do you use?
