### ISSUE TITLE
   Aimeos\MW\DB\Exception  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.mshop_locale_site' doesn't exist:

### ISSUE THREAD

**Issue by Jupeen** [aimeos/aimeos#52]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Aimeos\MW\DB\Exception  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.mshop_locale_site' doesn't exist:
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0

  at path-to-project\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
  > 75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      path-to-project\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:947

  2   Aimeos\MShop\Locale\Manager\Site\Standard::getSearchResults(Object(Aimeos\MW\DB\Connection\DBAL), "
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0
                                ")
      path-to-project\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:659

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by aimeos** [comment]
Can you please post the whole output so we can see what happend before?

**Comment by Jupeen** [comment]
this is from very start.
CPN@DESKTOP-EL1GQAD MINGW64 /g
$ composer create-project aimeos/aimeos myshop
Creating a "aimeos/aimeos" project at "./myshop"
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Installing aimeos/aimeos (2021.04.2)
  - Installing aimeos/aimeos (2021.04.2): Downloading (100%)
Created project in G:\\myshop
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
> @php -r "mkdir('public/files'); mkdir('public/preview'); mkdir('public/uploads');"
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Package operations: 122 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.11.0): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.22.1): Downloading (100%)
  - Installing phpoption/phpoption (1.7.5): Loading from cache
  - Installing vlucas/phpdotenv (v3.6.8): Downloading (100%)
  - Installing symfony/css-selector (v5.2.9): Downloading (100%)
  - Installing tijsverkoyen/css-to-inline-styles (2.2.3): Loading from cache
  - Installing symfony/polyfill-php80 (v1.22.1): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.22.1): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.22.1): Downloading (100%)
  - Installing symfony/var-dumper (v4.4.22): Downloading (100%)
  - Installing symfony/routing (v4.4.24): Downloading (100%)
  - Installing symfony/process (v4.4.22): Downloading (100%)
  - Installing symfony/polyfill-php73 (v1.22.1): Downloading (100%)
  - Installing psr/log (1.1.4): Downloading (100%)
  - Installing symfony/deprecation-contracts (v2.4.0): Downloading (connecting..Downloading (100%)
  - Installing symfony/polyfill-intl-normalizer (v1.22.1): Downloading (connectiDownloading (100%)
  - Installing symfony/polyfill-intl-idn (v1.22.1): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/mime (v5.2.9): Downloading (100%)
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing webmozart/assert (1.10.0): Downloading (100%)
  - Installing phpdocumentor/type-resolver (1.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (5.2.2): Downloading (connectinDownloading (100%)
  - Installing symfony/http-foundation (v4.4.23): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v1.1.9): Downloading (connectDownloading (100%)
  - Installing psr/container (1.1.1): Downloading (100%)
  - Installing symfony/event-dispatcher (v4.4.20): Downloading (100%)
  - Installing symfony/debug (v4.4.22): Downloading (100%)
  - Installing symfony/error-handler (v4.4.23): Downloading (100%)
  - Installing symfony/http-client-contracts (v2.4.0): Downloading (connecting..Downloading (100%)
  - Installing symfony/http-kernel (v4.4.24): Downloading (100%)
  - Installing symfony/finder (v4.4.24): Downloading (100%)
  - Installing symfony/service-contracts (v2.4.0): Downloading (100%)
  - Installing symfony/console (v4.4.24): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.22.1): Downloading (100%)
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing egulias/email-validator (2.1.25): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v6.2.7): Downloading (100%)
  - Installing ramsey/uuid (3.9.3): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing opis/closure (3.6.2): Downloading (100%)
  - Installing symfony/translation-contracts (v2.4.0): Downloading (connecting..Downloading (100%)
  - Installing symfony/translation (v4.4.24): Downloading (100%)
  - Installing nesbot/carbon (2.48.0): Downloading (100%)
  - Installing monolog/monolog (2.2.0): Downloading (100%)
  - Installing league/mime-type-detection (1.7.0): Downloading (100%)
  - Installing league/flysystem (1.1.3): Loading from cache
  - Installing league/commonmark (1.6.2): Downloading (100%)
  - Installing dragonmantank/cron-expression (v2.3.1): Downloading (connecting..Downloading (100%)
  - Installing doctrine/inflector (2.0.3): Loading from cache
  - Installing laravel/framework (v6.20.27): Downloading (100%)
  - Installing voku/portable-ascii (1.5.6): Downloading (100%)
  - Installing fideloper/proxy (4.4.1): Downloading (100%)
  - Installing php-parallel-lint/php-console-color (v0.3): Downloading (connectiDownloading (100%)
  - Installing php-parallel-lint/php-console-highlighter (v0.5): Downloading (coDownloading (100%)
  - Installing nikic/php-parser (v4.10.5): Downloading (100%)
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Loading from cache
  - Installing psy/psysh (v0.9.12): Downloading (100%)
  - Installing laravel/tinker (v1.0.10): Downloading (100%)
  - Installing laravel/ui (v1.3.0): Downloading (100%)
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing doctrine/event-manager (1.1.1): Downloading (100%)
  - Installing doctrine/cache (1.11.2): Downloading (100%)
  - Installing doctrine/deprecations (v0.5.3): Downloading (100%)
  - Installing doctrine/dbal (2.13.1): Downloading (100%)
  - Installing psr/http-factory (1.0.1): Downloading (100%)
  - Installing php-http/message-factory (v1.0.2): Downloading (100%)
  - Installing nyholm/psr7 (1.4.0): Downloading (100%)
  - Installing aimeos/map (2.2.0): Downloading (100%)
  - Installing aimeos/aimeos-core (2021.04.6): Downloading (100%)
  - Installing aimeos/ai-controller-frontend (2021.04.2): Downloading (connectinDownloading (100%)
  - Installing aimeos/ai-controller-jobs (2021.04.4): Downloading (connecting...Downloading (100%)
  - Installing aimeos/ai-client-jsonapi (2021.04.1):Downloading (100%)         )
  - Installing tecnickcom/tcpdf (6.4.1): Downloading (100%)
  - Installing aimeos/ai-client-html (2021.04.10): Downloading (100%)
  - Installing aimeos/ai-admin-jsonadm (2021.04.1): Downloading (100%)
  - Installing aimeos/ai-admin-jqadm (2021.04.7): Downloading (100%)
  - Installing aimeos/ai-laravel (2021.04.5): Downloading (100%)
  - Installing aimeos/ai-gettext (2021.04.1): Downloading (100%)
  - Installing aimeos/ai-swiftmailer (2021.04.1): Downloading (100%)
  - Installing laminas/laminas-zendframework-bridge (1.2.0): Downloading (connecDownloading (100%)
  - Installing laminas/laminas-diactoros (2.6.0): Downloading (100%)
  - Installing symfony/psr-http-message-bridge (v2.1.0): Downloading (connectingDownloading (100%)
  - Installing aimeos/aimeos-laravel (2021.04.3): Downloading (100%)
  - Installing aimeos/ai-cms-grapesjs (2021.04.3): Downloading (100%)
  - Installing scrivo/highlight.php (v9.18.1.6): Downloading (100%)
  - Installing facade/ignition-contracts (1.0.2): Downloading (100%)
  - Installing facade/flare-client-php (1.8.0): Downloading (100%)
  - Installing filp/whoops (2.12.1): Downloading (100%)
  - Installing facade/ignition (1.16.15): Downloading (100%)
  - Installing fzaninotto/faker (v1.9.2): Downloading (100%)
  - Installing hamcrest/hamcrest-php (v2.0.1): Loading from cache
  - Installing mockery/mockery (1.4.3): Downloading (100%)
  - Installing nunomaduro/collision (v3.2.0): Downloading (100%)
  - Installing sebastian/version (3.0.2): Downloading (100%)
  - Installing sebastian/type (2.3.1): Downloading (100%)
  - Installing sebastian/resource-operations (3.0.3): Downloading (connecting...Downloading (100%)
  - Installing sebastian/recursion-context (4.0.4): Downloading (100%)
  - Installing sebastian/object-reflector (2.0.4): Downloading (100%)
  - Installing sebastian/object-enumerator (4.0.4): Downloading (100%)
  - Installing sebastian/global-state (5.0.2): Downloading (100%)
  - Installing sebastian/exporter (4.0.3): Downloading (100%)
  - Installing sebastian/environment (5.1.3): Downloading (100%)
  - Installing sebastian/diff (4.0.4): Downloading (100%)
  - Installing sebastian/comparator (4.0.6): Downloading (100%)
  - Installing sebastian/code-unit (1.0.8): Downloading (100%)
  - Installing sebastian/cli-parser (1.0.1): Downloading (100%)
  - Installing phpunit/php-timer (5.0.3): Downloading (100%)
  - Installing phpunit/php-text-template (2.0.4): Downloading (100%)
  - Installing phpunit/php-invoker (3.1.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (3.0.5): Downloading (100%)
  - Installing theseer/tokenizer (1.2.0): Loading from cache
  - Installing sebastian/lines-of-code (1.0.3): Downloading (100%)
  - Installing sebastian/complexity (2.0.2): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Downloading (connectiDownloading (100%)
  - Installing phpunit/php-code-coverage (9.2.6): Downloading (100%)
  - Installing doctrine/instantiator (1.4.0): Downloading (100%)
  - Installing phpspec/prophecy (1.13.0): Downloading (100%)
  - Installing phar-io/version (3.1.0): Downloading (100%)
  - Installing phar-io/manifest (2.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.10.2): Downloading (100%)
  - Installing phpunit/phpunit (9.5.4): Downloading (100%)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-client-contracts suggests installing symfony/http-client-implementation
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing paragonie/random-lib (Provides RandomLib for use with the RandomLibAdapter)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing elasticsearch/elasticsearch (Allow sending log messages to an Elasticsearch server via official client)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongodb (Allow sending log messages to a MongoDB server (via driver))
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server (via library))
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing ext-memcached (Required to use the memcache cache driver.)
laravel/framework suggests installing ext-pcntl (Required to use all features of the queue worker.)
laravel/framework suggests installing ext-posix (Required to use all features of the queue worker.)
laravel/framework suggests installing ext-redis (Required to use the Redis cache and queue drivers (^4.0|^5.0).)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver, DynamoDb failed job storage and SES mail driver (^3.155).)
laravel/framework suggests installing fakerphp/faker (Required to use the eloquent factory builder (^1.9.1).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun mail driver and the ping methods on schedules (^6.3.1|^7.0.1).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^4.0).)
laravel/framework suggests installing predis/predis (Required to use the predis connector (^1.1.2).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^4.0).)
laravel/framework suggests installing symfony/cache (Required to PSR-6 cache bridge (^4.3.4).)
laravel/framework suggests installing wildbit/swiftmailer-postmark (Required to use Postmark mail driver (^3.0).)
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
facade/ignition suggests installing laravel/telescope (^2.0)
sebastian/global-state suggests installing ext-uopz (*)
sebastian/environment suggests installing ext-posix (*)
phpunit/php-invoker suggests installing ext-pcntl (*)
phpunit/php-code-coverage suggests installing ext-pcov (*)
phpunit/php-code-coverage suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Aimeos\MW\DB\Exception  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.mshop_locale_site' doesn't exist:
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0


  at G:\myshop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
  > 75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      G:\myshop\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:947

  2   Aimeos\MShop\Locale\Manager\Site\Standard::getSearchResults(Object(Aimeos\MW\DB\Connection\DBAL), "
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0
                                ")
      G:\myshop\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:659

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

CPN@DESKTOP-EL1GQAD MINGW64 /g

**Comment by aimeos** [comment]
The complete database setup hasn't been executed. Can you try with the latest composer (2.x)?

**Comment by Jupeen** [comment]
firstly I tried with composer 2, as it showed the same error I downgraded the composer and tried again and get the same error
Is there any error with php or mysql?

CPN@DESKTOP-EL1GQAD MINGW64 /g/myshop
$ mysql
ERROR 1045 (28000): Access denied for user 'CPN'@'localhost' (using password: NO)

CPN@DESKTOP-EL1GQAD MINGW64 /g/myshop
$ mysql --version
C:\xampp\mysql\bin\mysql.exe  Ver 15.1 Distrib 10.4.19-MariaDB, for Win64 (AMD64), source revision a4139f8d68bd31e80ff6202c093cd232c194ddfd

CPN@DESKTOP-EL1GQAD MINGW64 /g/myshop
$ php

CPN@DESKTOP-EL1GQAD MINGW64 /g/myshop
$ php -version
PHP 7.4.19 (cli) (built: May  4 2021 14:24:38) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

CPN@DESKTOP-EL1GQAD MINGW64 /g/myshop
$

**Comment by aimeos** [comment]
Your setup looks OK even though we know that Windows environments are not always working out of the box.
The commands that haven't been executed in your setup are:
https://github.com/aimeos/aimeos/blob/master/composer.json#L63-L68

**Comment by jonyshahin** [comment]
> Your setup looks OK even though we know that Windows environments are not always working out of the box.
> The commands that haven't been executed in your setup are:
> https://github.com/aimeos/aimeos/blob/master/composer.json#L63-L68

So how we solve this problem
Please advise

**Comment by aimeos** [comment]
You can run the composer script manually: `composer run-script post-create-project-cmd`

**Comment by aimeos** [comment]
We've found the problem and released a new version. Can you please run `composer create-project aimeos/aimeos myshop` again?

**Comment by netwaretcs** [comment]
I've the same problem.
Missing some tables after the installation process.

**Comment by aimeos** [comment]
> `Illuminate\Database\QueryException SQLSTATE[42S02]: Base table or view not found: 1146 Table 'a_data.sessions' doesn't exist (SQL: select * from `sessions`where`id`= caggjc0COf3dDb5DDoNuQffwU3RosaXTGE4ge4dp limit 1)`

`sessions` isn't an Aimeos table so you have installed another package which is causing this problem.

**Comment by netwaretcs** [comment]
Since I had the same problems as the person who opened this topic I tried installing laravel and then the aimeos package.

Maybe the sessions table is related to these steps:

`composer require laravel/jetstream
php artisan jetstream:install livewire
npm install && npm run dev`

**Comment by aimeos** [comment]
The tables are different so the source of the problem isn't the same.
Maybe you have to run `php artisan migrate` again to create your missing `session` table.

**Comment by DesimirDimitrov** [comment]
Try to upgrade the composer version to 2. It worked for me with the command composer self-update
