### ISSUE TITLE
Not Asked to enter the database name or email or any other parameters

### ISSUE THREAD

**Issue by jonyshahin** [aimeos/aimeos#53]
I try to create a new project but no asked to enter any parameters for the database 
so it thrown an error with database laravel not found
please advise

**Comment by aimeos** [comment]
Are you using Windows? Which composer version? Any more details?

**Comment by jonyshahin** [comment]
> Are you using Windows? Which composer version? Any more details?

Yes I am using Windows 10
Composer 2.0.14
PHP 7.4.9
MySQL 8.0.21

**Comment by aimeos** [comment]
Can you try a previous composer version (1.x or 2.0.x)? Maybe this one has problems with Windows. Also, your PHP version is rather old.

**Comment by jonyshahin** [comment]
I try composer version 2.0.13 and PHP version 7.4.19
that is what happened

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Aimeos\MW\DB\Exception  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.mshop_locale_site' doesn't exist:
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0


  at H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\DB\Statement\DBAL\Simple.php:75
    71|         {
    72|                 try {
    73|                         $result = $this->exec();
    74|                 } catch( \PDOException $e ) {
  > 75|                         throw new \Aimeos\MW\DB\Exception( $e->getMessage() . ': ' . $this->sql, $e->getCode() );
    76|                 }
    77|
    78|                 return new \Aimeos\MW\DB\Result\PDO( $result );
    79|         }

  Exception trace:

  1   Aimeos\MW\DB\Statement\DBAL\Simple::execute()
      H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:947

  2   Aimeos\MShop\Locale\Manager\Site\Standard::getSearchResults(Object(Aimeos\MW\DB\Connection\DBAL), "
                                        SELECT
                                                mlocsi."id" AS "locale.site.id", mlocsi."siteid" AS "locale.site.siteid",
                                                mlocsi."code" AS "locale.site.code", mlocsi."label" AS "locale.site.label",
                                                mlocsi."config" AS "locale.site.config", mlocsi."status" AS "locale.site.status",
                                                mlocsi."editor" AS "locale.site.editor", mlocsi."mtime" AS "locale.site.mtime",
                                                mlocsi."ctime" AS "locale.site.ctime"
                                        FROM "mshop_locale_site" AS mlocsi
                                        WHERE mlocsi."level" = 0 AND ( mlocsi."code" = 'default' )
                                        ORDER BY mlocsi."id" ASC
                                        LIMIT 1 OFFSET 0
                                ")
      H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop\vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Locale\Manager\Site\Standard.php:659

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by aimeos** [comment]
We've found the problem and released a new version. Can you please run composer create-project aimeos/aimeos myshop again?

**Comment by jonyshahin** [comment]
Dear,
Thank you very much the problem is solved. However, I face a new problem when migrating the database.
Please Advise

@php artisan migrate
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (1.5 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))

  at H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop2\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop2\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
      H:\freelance\LaravelDaily\aimeos_ecommerce_system\myshop2\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:114

  Please use the argument -v to see more details.
Script @php artisan migrate handling the post-create-project-cmd event returned with error code 1

**Comment by aimeos** [comment]
Your database version is too old, see here for a workaround: https://github.com/aimeos/aimeos-laravel#database
