### ISSUE TITLE
Item with ID "2" in "customer.id" not found

### ISSUE THREAD

**Issue by hyltonmillar-blsky** [aimeos/aimeos#57]
After a fresh install.
I go to locales->sites
Add a new site.
When I try to change to the new site the error appears:
Item with ID "2" in "customer.id" not found
vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php:618
Am I missing something?
I get the same error when trying to create as new site with "php artisan ameos:setup test001"

**Comment by aimeos** [comment]
Your user you are logged in with (probably admin of the first "default" site) is bound to the "default" site and is not available in the second site you have created. If you log out, the error will disappear.

**Comment by hyltonmillar-blsky** [comment]
Logged out and back in. Still get the same error. My user table has the following values 
![image](https://user-images.githubusercontent.com/55060984/123408691-92918180-d5ad-11eb-85ae-044a918bf239.png)
Am I correct in assuming that if I login as a superuser, I should be able to switch between sites, or is there a away to bind superusers to each site?

**Comment by aimeos** [comment]
Yes, if you remove the value in `siteid`, the user won't be bound to any site.

**Comment by hyltonmillar-blsky** [comment]
removed the value in siteid, working now, thank you

**Comment by aimeos** [comment]
The site ID for superusers is now empty by default:
https://github.com/aimeos/aimeos-laravel/commit/8fb55264629e4c4abfc435715ebee07da2fb68e6
