### ISSUE TITLE
Home page reload itself

### ISSUE THREAD

**Issue by michele-grifa** [aimeos/aimeos#59]
Environment
Version: 2021.07.04
Operating system: Linux
Php Version: 8.0.9

Describe the bug
When i use the following command, artisan serve --host=192.168.0.34 --port=8000, to start the integrated server instead of artisan serve, when i open the home page, it reload itself infinitely until i stop the artisan command. The admin page doesn't have this problem.

To Reproduce
1. Start the integrated server with the command artisan serve --host=YOURIP --port=8000 or any host different than 127.0.0.1
2. Go on the home page
3. The page reload infinitely

Expected behavior
The page should not reload itself

**Comment by aimeos** [comment]
Duplicate for https://github.com/aimeos/aimeos-laravel/issues/398
