### ISSUE TITLE
Install Error: php artisan aimeos:setup --option=setup/default/demo:1

### ISSUE THREAD

**Issue by e-solutions** [aimeos/aimeos#6]
Hi,

When I run the install command I get the following error. I am using pgsql as my DB but I was under the impression that this was supported.

php artisan aimeos:setup --option=setup/default/demo:1

In DBAL.php line 99:

  An exception occurred while executing 'SET SESSION sort_buffer_size=2097144
  ; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'':

  SQLSTATE[42601]: Syntax error: 7 ERROR:  cannot insert multiple commands in
  to a prepared statement

**Comment by aimeos** [comment]
PostgreSQL is supported but not by the distribution out of the box.

You have to change some configuration settings before the database setup and this is easiest done if you create a Laravel skeleton application first and do the steps for the setup manually:
https://github.com/aimeos/aimeos-laravel#important-notice

For PostgreSQL, please have a look at this article for the required settings:
https://aimeos.org/docs/Developers/Library/Database_support

**Comment by e-solutions** [comment]
Thanks will do.

**Comment by gbolarhan** [comment]
I'm unable to access this page https://aimeos.org/docs/Developers/Library/Database_support. Help!
