### ISSUE TITLE
Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by yungifez** [aimeos/aimeos#61]
I'm using PHP 8

and i keep getting this error 

Symfony\Component\Debug\Exception\FatalThrowableError
Cannot use a scalar value as an array

vendor\aimeos\aimeos-core\lib\mshoplib\src\MShop\Index\Manager\Attribute\Standard.php:81

any idea?

**Comment by aimeos** [comment]
Might be a bug in the PHP 8 interpreter. Does it work with PHP 7.4?
Do you have a stack trace?

**Comment by yungifez** [comment]
I do 

Yeah I figured that's it's a bug with php 8

Because I recently upgraded it to php 8

And it works on my remote server using php 7

I'll probably just use docker for development in my local env
