### ISSUE TITLE
duplicate ai-* 

### ISSUE THREAD

**Issue by godadada** [aimeos/aimeos#62]
I am getting this Exception when doing php artisan setup, please help.
Plateform: Aimeos 21.07, PHP7.4, ubuntu20.04, mysql5.7

Exception 

  Extension "ai-admin-jqadm" exists twice in "<projectroot>/vendor/aimeos/ai-admin-jqadm" and in "<projectroot>/ext/ai-admin-jqadm"

**Comment by godadada** [comment]
all directories are under project root.

**Comment by aimeos** [comment]
You are upgrading from an earlier version. Please read the upgrade guide:
https://aimeos.org/docs/latest/laravel/setup/#upgrade-to-202107
