### ISSUE TITLE
SESSION_LIFETIME not working

### ISSUE THREAD

**Issue by godadada** [aimeos/aimeos#66]
install aimeos 21.07, create an account, and close the browser until after SESSION_LIFETIME expires. restart the browser, enter url http://localhost:8000/profile. you are still logged in.

other info: ubuntu20/mysql5.7

**Comment by aimeos** [comment]
Are you still logged in or is this page from the browser cache?
You can check by pressing Ctrl+Shift+R

**Comment by godadada** [comment]
You are right. Thanks.

Best Wishes,   Chunde Shi
***@***.*** 

    On Thursday, September 2, 2021, 01:58:06 AM EDT, Aimeos ***@***.***> wrote:  
 
 


Are you still logged in or is this page from the browser cache?
You can check by pressing Ctrl+Shift+R

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aimeos** [comment]
This should have been fixed in the latest version:
https://github.com/aimeos/aimeos-laravel/commit/63f18cc5edb12c911439f1ec5b01d32483e433d7#diff-3d4e8a037ec76b994540c431f7a998d7f8905a911094ab030202631541e92e53
