### ISSUE TITLE
Potential Localization Bug

### ISSUE THREAD

**Issue by godadada** [aimeos/aimeos#67]
install aimeos/aimeos 21.07 according to the aimeos/aimeos github.com document.
set locale to 'de' in file config/app.php: 'locale' => 'de'
Run the installation. Only http://localhost:8000/admin is 'de' German, the rest pages are still  default 'en' English.

I tried version 2018/2019/2020, behaves same.

Please advice.

**Comment by aimeos** [comment]
The app.locale setting is used if no GET or route parameter is available:
https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/Locale.php#L58

But you still need to set up the allowed site/locale/currency combinations in the Locale > Locale panel of the admin backend.
