### ISSUE TITLE
Pin feature throws error

### ISSUE THREAD

**Issue by Sm1lEE** [aimeos/aimeos#68]
When clicking the pin icon on a product detail page, the following error is thrown: https://flareapp.io/share/LPlrgaD5

![screenshot-pin-on-demo-site](https://user-images.githubusercontent.com/2184676/139527194-fe4bc0a0-f1bc-4fc4-8d62-fce5919ca811.png)

I've followed the [installation instructions](https://github.com/aimeos/aimeos#installation) on a local machine.

- same behavior with PHP 8.0.12 and 7.4.25
- happens also in a new private tab
- tested both when logged in and logged out

**Comment by aimeos** [comment]
Thanks for the issue report. The problem was caused due to a missing config and has been fixed in 2021.10.x-dev. Use this to create a new installation using the fixed code:
```
composer create-project aimeos/aimeos:2021.10.x-dev
```
