### ISSUE TITLE
Root composer.json requires aimeos/aimeos-laravel 2021.07.* -> satisfiable by aimeos/aimeos-laravel[2021.07.1, ..., 2021.07.x-dev].

### ISSUE THREAD

**Issue by lincontroy** [aimeos/aimeos#69]
Check on this

**Comment by aimeos** [comment]
Details please! What did you do and what are your environment specs?

**Comment by lincontroy** [comment]
the normal installation of a script.
git clone https://github.com/aimeos/aimeos
composer install
I cloned the repository on my local PC 
Composer version 2.0.13 2021-04-27 13:11:08
PHP 7.3.27

**Comment by lincontroy** [comment]
what other piece of information do you need

**Comment by aimeos** [comment]
Please use the command like in the README:
```
composer create-project aimeos/aimeos myshop
```

**Comment by zambodaniel** [comment]
Here's the output:
![Screenshot from 2021-11-02 10-25-53](https://user-images.githubusercontent.com/3462880/139820584-9ee6b5b9-0d18-486c-a67c-286605e727a3.png)

**Comment by aimeos** [comment]
Aimeos requires composer 2.1+
