### ISSUE TITLE
Locale item for site "default" not found 

### ISSUE THREAD

**Issue by Dhaoui0Chaher** [aimeos/aimeos#72]
After i install the aimeos project in a shared host, I get this error 
Locale item for site “default” not found 

what i do to solve the problem :
1/ chnage the `SHOP_MULTILOCALE` to true  -> not solve the problem 
2/ php artisan aimeos:setup --option=setup/default/demo:1 -> not solve the problem 
3/ check the `sort_buffer_size` Iit's 2M 

to get more information about the bug you can visit the [domain name](https://laboratoiresnerolina.com.tn/)

**Comment by aimeos** [comment]
Check in the Locale > Locale panel of the admin backend if there's an entry for the "default" site with language "en" (because the main page redirects to `/en` due to your `locale` setting in your ./config/app.php).

**Comment by Dhaoui0Chaher** [comment]
i can't access the admin panel due to the same problem 
but the project work correctly in the local

**Comment by aimeos** [comment]
- add a record to the `mshop_locale` table or
- delete all records in `mshop_locale` table and run `php artisan aimeos:setup --option=setup/default/demo:1` again

Most likely, the problem is that you have a locale entry in you `mshop_locale` table that doesn't fit to your `locale` setting in ./config/app.php

**Comment by Dhaoui0Chaher** [comment]
It works now thanks, 
but the views missing css as mentioned in the console

**Comment by aimeos** [comment]
Installing Laravel/Aimeos in your document root is not supported. The document root of your web server must point to the ./public/ directory
