### ISSUE TITLE
Not able to run the extensions. Missing phing file in vendors folder

### ISSUE THREAD

**Issue by rahulhhb** [aimeos/aimeos#74]
We not able to work with extensions. As per the documentation we run the setup with phing.xml file but in new installation of project phing.xml file is missing and we are not able to install the extension. Can you please guide us on the same. What are the changes made in the update.

We have attahced 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/92012215/143397323-23c543fc-04b0-4137-879e-f45acdc939e9.png)

**Comment by aimeos** [comment]
Please read this how to install your own extensions:
https://aimeos.org/docs/latest/developer/extensions/#location
