### ISSUE TITLE
while running composer install cmd getting problem

### ISSUE THREAD

**Issue by nanijb** [aimeos/aimeos#75]
Problem 1
    - aimeos/aimeos-core dev-master requires php ~7.1||^8.0.10 -> your php version (8.0.5) does not satisfy that requirement.
    - aimeos/ai-cms-grapesjs dev-master requires aimeos/aimeos-core dev-master -> satisfiable by aimeos/aimeos-core[dev-master].
    - Root composer.json requires aimeos/ai-cms-grapesjs dev-master -> satisfiable by aimeos/ai-cms-grapesjs[dev-master].

**Comment by aimeos** [comment]
You need at least PHP 8.0.10 or PHP 7.4.x
