### ISSUE TITLE
curl error 60 while downloading

### ISSUE THREAD

**Issue by Henry17888** [aimeos/aimeos#76]
Hi,
I find it's a fantastic project.
When I want to install it on my localhost with code: composer create-project aimeos/aimeos myshop, I get an error as below: `[Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.aimeos.org/aimeoscom/packa
  ges.json: SSL certificate problem: certificate has expired
`
I also tried to download the master package and upload to my server then I run the command: composer update, and I got same error.
My server is Debian+LAMP. All the versions meet the requirement.
Could someone help me on this? thank you.

**Comment by aimeos** [comment]
You must update your Debian system to get the current SSL root certificates.

**Comment by Henry17888** [comment]
Thank you Aimeos.
I have updated my system with code: sudo apt update && sudo apt upgrade. While, I still get the same error

**Comment by aimeos** [comment]
Which Debian version do you use?
If you check the URL in your browser, it works without problems: https://packages.aimeos.org/aimeoscom/packages.json

**Comment by Henry17888** [comment]
here is my os information
`root@debian:~# hostnamectl
   Static hostname: debian
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 1508b893fb3a453da3b3e1aefb39bf28
           Boot ID: 393d4ee3b6a446958bcb14f19ecc56bb
    Virtualization: vmware
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-18-amd64
      Architecture: x86-64
`

**Comment by Henry17888** [comment]
Apache:2.4.48
MYSQL: 5.7.34
PHP: 7.4

**Comment by aimeos** [comment]
Please try the command `update-ca-certificates`

**Comment by Henry17888** [comment]
thank you. but I still get this error:
`root@debian:~# update-ca-certificates
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
root@debian:~# cd /www/wwwroot
root@debian:/www/wwwroot# php composer create-project aimeos/aimeos myshop -vvv
Running 2.1.14 (2021-11-30 10:51:43) with PHP 7.4.20 on Linux / 4.19.0-18-amd64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Loading config file /root/.config/composer/auth.json
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
Creating a "aimeos/aimeos" project at "./myshop"
Loading config file /root/.config/composer/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/www/wwwroot): git branch -a --no-color --no-abbrev -v
Executing command (/www/wwwroot): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/www/wwwroot): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/www/wwwroot): hg branch
Executing command (/www/wwwroot): fossil branch list
Executing command (/www/wwwroot): fossil tag list
Executing command (/www/wwwroot): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /root/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /root/.cache/composer/repo/https---repo.packagist.org/provider-aimeos~aimeos.json from cache
Downloading https://repo.packagist.org/p2/aimeos/aimeos.json if modified
[304] https://repo.packagist.org/p2/aimeos/aimeos.json
Installing aimeos/aimeos (2021.10.3)
Reading /root/.cache/composer/files/aimeos/aimeos/1c3abaf4aca124f97c7f20f747ed2985bdedeb98.zip from cache
  - Loading aimeos/aimeos (2021.10.3) from cache
  - Installing aimeos/aimeos (2021.10.3): Extracting archive
Executing async command (CWD): '/bin/unzip' -qq '/www/wwwroot/vendor/composer/tmp-ff8a04b102d436cb86d096f55cc4c1bc' -d '/www/wwwroot/vendor/composer/13e72464'
Executing async command (CWD): rm -rf '/www/wwwroot/vendor/composer/13e72464'
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/
Created project in /www/wwwroot/myshop
Reading ./composer.json (/www/wwwroot/myshop/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/myshop/composer.json)
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

> post-root-package-install: @php -r "file_exists('.env') || copy('.env.example', '.env');"
Executing command (CWD): '/www/server/php/74/bin/php' -d allow_url_fopen='1' -d disable_functions='passthru,system,chroot,chgrp,popen,pcntl_exec,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,imap_open,apache_setenv' -d memory_limit='1536M' -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Reading ./composer.json (/www/wwwroot/myshop/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/myshop/composer.json)
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json



  [Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.aimeos.org/aimeoscom/packa
  ges.json: SSL certificate problem: certificate has expired


Exception trace:
 () at phar:///www/wwwroot/composer/src/Composer/Util/Http/CurlDownloader.php:354
 Composer\Util\Http\CurlDownloader->tick() at phar:///www/wwwroot/composer/src/Composer/Util/HttpDownloader.php:403
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///www/wwwroot/composer/src/Composer/Util/HttpDownloader.php:372
 Composer\Util\HttpDownloader->wait() at phar:///www/wwwroot/composer/src/Composer/Util/HttpDownloader.php:108
 Composer\Util\HttpDownloader->get() at phar:///www/wwwroot/composer/src/Composer/Repository/ComposerRepository.php:1219
 Composer\Repository\ComposerRepository->fetchFile() at phar:///www/wwwroot/composer/src/Composer/Repository/ComposerRepository.php:934
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///www/wwwroot/composer/src/Composer/Repository/ComposerRepository.php:586
 Composer\Repository\ComposerRepository->hasProviders() at phar:///www/wwwroot/composer/src/Composer/Repository/ComposerRepository.php:397
 Composer\Repository\ComposerRepository->loadPackages() at phar:///www/wwwroot/composer/src/Composer/DependencyResolver/PoolBuilder.php:349
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///www/wwwroot/composer/src/Composer/DependencyResolver/PoolBuilder.php:206
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///www/wwwroot/composer/src/Composer/Repository/RepositorySet.php:259
 Composer\Repository\RepositorySet->createPool() at phar:///www/wwwroot/composer/src/Composer/Installer.php:427
 Composer\Installer->doUpdate() at phar:///www/wwwroot/composer/src/Composer/Installer.php:271
 Composer\Installer->run() at phar:///www/wwwroot/composer/src/Composer/Command/CreateProjectCommand.php:267
 Composer\Command\CreateProjectCommand->installProject() at phar:///www/wwwroot/composer/src/Composer/Command/CreateProjectCommand.php:164
 Composer\Command\CreateProjectCommand->execute() at phar:///www/wwwroot/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///www/wwwroot/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///www/wwwroot/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///www/wwwroot/composer/src/Composer/Console/Application.php:327
 Composer\Console\Application->doRun() at phar:///www/wwwroot/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///www/wwwroot/composer/src/Composer/Console/Application.php:128
 Composer\Console\Application->run() at phar:///www/wwwroot/composer/bin/composer:73
 require() at /www/wwwroot/composer:29

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]`

**Comment by Henry17888** [comment]
Thank you Aimeos, but still have the same error.
`root@debian:~# apt-get install ca-certificates -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20200601~deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@debian:~# cd /www/wwwroot/myshop/
root@debian:/www/wwwroot/myshop# composer update -vvv
Running 2.1.14 (2021-11-30 10:51:43) with PHP 7.4.20 on Linux / 4.19.0-18-amd64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Reading ./composer.json (/www/wwwroot/myshop/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/myshop/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/www/wwwroot/myshop): git branch -a --no-color --no-abbrev -v
Executing command (/www/wwwroot/myshop): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/www/wwwroot/myshop): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/www/wwwroot/myshop): hg branch
Executing command (/www/wwwroot/myshop): fossil branch list
Executing command (/www/wwwroot/myshop): fossil tag list
Executing command (/www/wwwroot/myshop): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Loading composer repositories with package information
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json


  [Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.aimeos.org/aimeoscom/packa
  ges.json: SSL certificate problem: certificate has expired


Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:354
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:403
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:372
 Composer\Util\HttpDownloader->wait() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:108
 Composer\Util\HttpDownloader->get() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:1219
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:934
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:586
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:397
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:349
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:206
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/bin/composer/src/Composer/Repository/RepositorySet.php:259
 Composer\Repository\RepositorySet->createPool() at phar:///usr/bin/composer/src/Composer/Installer.php:427
 Composer\Installer->doUpdate() at phar:///usr/bin/composer/src/Composer/Installer.php:271
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:248
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:327
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:128
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:73
 require() at /usr/bin/composer:29

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
`

**Comment by aimeos** [comment]
Does it help if you do the steps from the script?
https://github.com/xenetis/letsencrypt-expiration/blob/main/letsencrypt-expiration.sh

**Comment by Henry17888** [comment]
Hi，
I have run the code: apt-get install ca-certificates -y, but still get the same error.

**Comment by aimeos** [comment]
There's another command in the script:
https://github.com/xenetis/letsencrypt-expiration/blob/main/letsencrypt-expiration.sh#L12-L13

If that doesn't work, there are also commands for manually updating the certificates in https://github.com/xenetis/letsencrypt-expiration/blob/main/letsencrypt-expiration.sh

**Comment by Henry17888** [comment]
yes, I tried.
here are the errors:
`root@debian:~# sh letsencrypt-expiration.sh
Hit:1 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
ca-certificates is already the newest version (20200601~deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@debian:~# cd /www/wwwroot
root@debian:/www/wwwroot# composer create-project aimeos/aimeos myshop -vvv
Running 2.1.14 (2021-11-30 10:51:43) with PHP 7.4.20 on Linux / 4.19.0-18-amd64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Loading config file /root/.config/composer/auth.json
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
Creating a "aimeos/aimeos" project at "./myshop"
Loading config file /root/.config/composer/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/www/wwwroot): git branch -a --no-color --no-abbrev -v
Executing command (/www/wwwroot): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/www/wwwroot): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/www/wwwroot): hg branch
Executing command (/www/wwwroot): fossil branch list
Executing command (/www/wwwroot): fossil tag list
Executing command (/www/wwwroot): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /root/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /root/.cache/composer/repo/https---repo.packagist.org/provider-aimeos~aimeos.json from cache
Downloading https://repo.packagist.org/p2/aimeos/aimeos.json if modified
[200] https://repo.packagist.org/p2/aimeos/aimeos.json
Writing /root/.cache/composer/repo/https---repo.packagist.org/provider-aimeos~aimeos.json into cache
Installing aimeos/aimeos (2021.10.4)
  - Downloading aimeos/aimeos (2021.10.4)
Downloading https://api.github.com/repos/aimeos/aimeos/zipball/388a1c3cd6e28fdff4e39e54cd1b38505a36472d
[302] https://api.github.com/repos/aimeos/aimeos/zipball/388a1c3cd6e28fdff4e39e54cd1b38505a36472d
Following redirect (1) https://codeload.github.com/aimeos/aimeos/legacy.zip/388a1c3cd6e28fdff4e39e54cd1b38505a36472d
[200] https://codeload.github.com/aimeos/aimeos/legacy.zip/388a1c3cd6e28fdff4e39e54cd1b38505a36472d
Writing /root/.cache/composer/files/aimeos/aimeos/58c0b1e449fd2000f9347735c7aac15b3ee8d7d9.zip into cache from /www/wwwroot/vendor/composer/tmp-995761c1ef6dc495ae47a4f1a273169a
  - Installing aimeos/aimeos (2021.10.4): Extracting archive
Executing async command (CWD): '/usr/bin/unzip' -qq '/www/wwwroot/vendor/composer/tmp-995761c1ef6dc495ae47a4f1a273169a' -d '/www/wwwroot/vendor/composer/87bff8f9'
Executing async command (CWD): rm -rf '/www/wwwroot/vendor/composer/87bff8f9'
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/
Created project in /www/wwwroot/myshop
Reading ./composer.json (/www/wwwroot/myshop/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/myshop/composer.json)
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

> post-root-package-install: @php -r "file_exists('.env') || copy('.env.example', '.env');"
Executing command (CWD): '/www/server/php/74/bin/php' -d allow_url_fopen='1' -d disable_functions='passthru,system,chroot,chgrp,popen,pcntl_exec,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,imap_open,apache_setenv' -d memory_limit='1536M' -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Downloading https://packages.aimeos.org/aimeoscom/packages.json
Reading ./composer.json (/www/wwwroot/myshop/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/myshop/composer.json)
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json



  [Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.aimeos.org/aimeoscom/packa
  ges.json: SSL certificate problem: certificate has expired


Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:354
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:403
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:372
 Composer\Util\HttpDownloader->wait() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:108
 Composer\Util\HttpDownloader->get() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:1219
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:934
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:586
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:397
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:349
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:206
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/bin/composer/src/Composer/Repository/RepositorySet.php:259
 Composer\Repository\RepositorySet->createPool() at phar:///usr/bin/composer/src/Composer/Installer.php:427
 Composer\Installer->doUpdate() at phar:///usr/bin/composer/src/Composer/Installer.php:271
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/CreateProjectCommand.php:267
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/bin/composer/src/Composer/Command/CreateProjectCommand.php:164
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:327
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:128
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:73
 require() at /usr/bin/composer:29

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

root@debian:/www/wwwroot#
`

**Comment by aimeos** [comment]
What about manually updating the certificates like used here:
https://github.com/xenetis/letsencrypt-expiration/blob/main/letsencrypt-expiration.sh#L5-L9

**Comment by Henry17888** [comment]
My system is Debian 10, not jessie. 
and I tried the code as below:
`root@debian:/www/wwwroot/myshop#   sed -i -e 's|mozilla/DST_Root_CA_X3.crt|#mozilla/DST_Root_CA_X3.crt|g' /etc/ca-certificates.conf
root@debian:/www/wwwroot/myshop#   sed -i -e 's|mozilla/ISRG_Root_X1.crt|#mozilla/ISRG_Root_X1.crt|g' /etc/ca-certificates.conf
root@debian:/www/wwwroot/myshop#   wget https://letsencrypt.org/certs/lets-encrypt-r3.pem -P /usr/local/share/ca-certificates/
--2021-12-08 16:41:28--  https://letsencrypt.org/certs/lets-encrypt-r3.pem
Resolving letsencrypt.org (letsencrypt.org)... 138.197.207.178, 54.241.246.27, 2600:1f1c:471:9d00:294d:a28a:5d94:bbfa, ...
Connecting to letsencrypt.org (letsencrypt.org)|138.197.207.178|:443... connected.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
HTTP request sent, awaiting response... 200 OK
Length: 1826 (1.8K) [application/x-pem-file]
Saving to: ‘/usr/local/share/ca-certificates/lets-encrypt-r3.pem.1’

lets-encrypt-r3.pem 100%[===================>]   1.78K  --.-KB/s    in 0s

2021-12-08 16:41:29 (4.54 MB/s) - ‘/usr/local/share/ca-certificates/lets-encrypt-r3.pem.1’ saved [1826/1826]

root@debian:/www/wwwroot/myshop#   wget https://letsencrypt.org/certs/isrgrootx1.pem -P /usr/local/share/ca-certificates/
--2021-12-08 16:41:29--  https://letsencrypt.org/certs/isrgrootx1.pem
Resolving letsencrypt.org (letsencrypt.org)... 138.197.207.178, 54.241.246.27, 2600:1f1c:471:9d00:294d:a28a:5d94:bbfa, ...
Connecting to letsencrypt.org (letsencrypt.org)|138.197.207.178|:443... connected.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
HTTP request sent, awaiting response... 200 OK
Length: 1939 (1.9K) [application/x-pem-file]
Saving to: ‘/usr/local/share/ca-certificates/isrgrootx1.pem.1’

isrgrootx1.pem.1    100%[===================>]   1.89K  --.-KB/s    in 0s

2021-12-08 16:41:30 (31.1 MB/s) - ‘/usr/local/share/ca-certificates/isrgrootx1.pem.1’ saved [1939/1939]

root@debian:/www/wwwroot/myshop#   update-ca-certificates -f
bash: update-ca-certificates: command not found
root@debian:/www/wwwroot/myshop#
`

**Comment by Henry17888** [comment]
after this, I run composer update in my shop root get the same error:
`[Composer\Downloader\TransportException]
  curl error 60 while downloading https://packages.aimeos.org/aimeoscom/packa
  ges.json: SSL certificate problem: certificate has expired

`

**Comment by aimeos** [comment]
We don't know what else could be done besides upgrading to the current stable Debian version.

**Comment by Henry17888** [comment]
Thank you so much.
Maybe I will try Aimeos later.
have a good day.

**Comment by trangunghoa** [comment]
Hi I have the same issue, I'm using macbook 
PHP 7.3.29 (cli) (built: Sep 30 2021 13:17:10) ( NTS )
Composer version 2.1.12 2021-11-09 16:02:04

**Comment by aimeos** [comment]
If updating the TLS certificates on your machine doesn't work, there's no known workaround for that LetsEncrypt issue yet. Try to install Aimeos at another machine.

**Comment by trangunghoa** [comment]
for me disable tls and it's working perfectly.  thank you
this is the command for someone need to fix. `composer config -g -- disable-tls true`
