### ISSUE TITLE
 ALTER TABLE users_address ADD CONSTRAINT fk_lvuad_pid FOREIGN KEY (parentid) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE

### ISSUE THREAD

**Issue by chinarchakole** [aimeos/aimeos#77]
windows environment so using wamp server for server process
composer version 2.1.14
php version PHP 7.4.26
laravel version ^8.54
aimeos version 2021.10

I followed the below mentioned steps

1)wget https://getcomposer.org/download/latest ... poser.phar -O composer

2) config/database.php
'connections' => [
'mysql' => [
// ...
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
// ...
]
]

3)php composer create-project aimeos/aimeos myshop

but still facing the issue: ![Screenshot (212)](https://user-images.githubusercontent.com/30881896/147058244-3515a034-6b45-4095-bc3e-92e79eed17ac.png)

provide a solution in this

**Comment by aimeos** [comment]
Explaination is available here: https://aimeos.org/help/viewtopic.php?f=15&t=4108
