### ISSUE TITLE
Trying to create(migrate) a new table 

### ISSUE THREAD

**Issue by swhhhub** [aimeos/aimeos#78]
created a file aimeos\aimeos-core\lib\mshoplib\setup\default\schema\message.php with following code
return array(
	'table' => array(
		'mshop_message' => function( \Doctrine\DBAL\Schema\Schema $schema ) {

			$table = $schema->createTable( 'mshop_message' );
			$table->addOption( 'engine', 'InnoDB' );

			$table->addColumn( 'id', 'bigint', ['autoincrement' => true] );
			$table->addColumn( 'siteid', 'string', ['length' => 255] );
			$table->addColumn( 'domain', 'string', ['length' => 32] );
			$table->addColumn( 'refid', 'string', ['length' => 36] );
			$table->addColumn( 'customerid', 'string', ['length' => 36] );
			$table->addColumn( 'prodid', 'string', ['length' => 36] );
			$table->addColumn( 'name', 'string', ['length' => 32] );
			$table->addColumn( 'status', 'smallint', [] );
			$table->addColumn( 'subject', 'text', ['length' => 0xffff] );
			$table->addColumn( 'mtime', 'datetime', [] );
			$table->addColumn( 'ctime', 'datetime', [] );
			$table->addColumn( 'editor', 'string', ['length' => 255] );

			$table->setPrimaryKey( ['id'], 'pk_msmes_id' );
			$table->addUniqueIndex( ['siteid', 'customerid', 'domain', 'refid'], 'unq_msmes_sid_cid_dom_rid' );
			$table->addIndex( ['siteid', 'domain', 'refid', 'status', 'ctime'], 'idx_msmes_sid_dom_rid_sta_ct' );
			$table->addIndex( ['siteid', 'domain', 'refid', 'status'], 'idx_msmes_sid_dom_rid_sta' );
			$table->addIndex( ['siteid', 'domain', 'customerid', 'mtime'], 'idx_msmes_sid_dom_cid_mt' );
			$table->addIndex( ['siteid', 'rating', 'domain'], 'idx_msmes_sid_rate_dom' );

			return $schema;
		},
	),
);
and thn run 'php artisan migrate' command.. a table is created in database named mshop_message with only three fields 'id','created_at','updated_at'.. why all the other fields are not there in the table. 
Please correct me where I am doing wrong..
And how can I create table with all the fields I want in my message table.

**Comment by aimeos** [comment]
If your table contains a `created_at` and `updated_at` columns, they have been created by a Laravel model/migration. To create the table you've outlined above, you need to add a setup task like described here:
https://aimeos.org/docs/latest/infrastructure/schema-migrations/#tables-for-new-domains

**Comment by swhhhub** [comment]
Thanks!!But fron the documentation link its not clear to me that  What should be the path for TablesCreateMydomain.php file and after creating this file what command should be execute so that table is created by Aimeos only.

**Comment by aimeos** [comment]
Store the setup task in `./lib/custom/setup/` of your extension
