### ISSUE TITLE
Want to fetch login customer id

### ISSUE THREAD

**Issue by swhhhub** [aimeos/aimeos#79]
Hi, 
I want to fetch login customer id at catalog detail page, As  I am adding  a functionality for send message by customer to product  supplier.. so need to store customerid and customername in backend.. but I am not able to fetch customer id in client\html\templates\catalog\detail\body-standard.php file.

**Comment by aimeos** [comment]
The customer ID is available as `$this->contextUserId`:
https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Common/Decorator/Context.php#L45

Please use the Aimeos forum for help as Github is only for bugs and features:
https://aimeos.org/help

**Comment by swhhhub** [comment]
Thanks!! Next time I will take care of it.
