### ISSUE TITLE
cannot split search and categories/attributes from @section('aimeos_nav') 

### ISSUE THREAD

**Issue by prasan2421** [aimeos/aimeos#8]
i have tried creating a new files in templates creating new category/filter file but it cannot solve the problem. should i create a new extension for it?

**Comment by aimeos** [comment]
The current dev-master version contains now separate components for attribute, search and tree parts of the catalog filter: https://github.com/aimeos/ai-client-html/commit/37f0cca3a77742f1227f8fd777ba05270e25079f
