### ISSUE TITLE
Issue in aimeos:setup

### ISSUE THREAD

**Issue by amitbindal09** [aimeos/aimeos#80]
Hi Team,

I resolved below issue by changing the mysql default engine to InnoDB.

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`)).`

Now, it breaks after 
`Checking table "mshop_product_property_type":                     Script App\Composer::setup handling the post-create-project-cmd event terminated with an exception`

![image](https://user-images.githubusercontent.com/10669175/149618614-ff61d58d-22d8-44e0-9eca-641722cb7d1a.png)

I have tried below cmd as well but getting same error.

```
php artisan migrate
php artisan vendor:publish --tag=public --force
php artisan aimeos:setup --option=setup/default/demo:1
php artisan aimeos:account --super <email address>
```

PHP Version: 7.2.34
MySql Version: 10.3.32-MariaDB

Thanks
Amit Bindal

**Comment by aimeos** [comment]
It seems like your DB is creating MyISAM tables by default:
https://dba.stackexchange.com/questions/283655/mariadb-error-1071-specified-key-was-too-long-max-key-length-is-1000-bytes

Can you confirm that the `users` table uses MyISAM as table engine?

**Comment by amitbindal09** [comment]
As I changed default engine to **InnoDB**, all tables including `users` are **InnoDB** type now.
