### ISSUE TITLE
How to create decorator and use it in client/html/templates

### ISSUE THREAD

**Issue by swhhhub** [aimeos/aimeos#83]
Hi,
Created a category decorator to display categories on my catalog list page
client\html\src\Client\Html\Common\Decorator
here I created a Category.php
and some methods I defined in this class..

Now how I can config or call method of my Category Decorator in client\html\templates\catalog\lists\body-standard.php
I checked documentation provided at below link-
[https://aimeos.org/docs/latest/frontend ... figuration](https://aimeos.org/docs/latest/frontend/html/extend-components/#configuration)

But from this it is not clear to me how to configure.. File structure where I need to add
client/html/catalog/lists/decorators/global = ['Category']

Please help to make me understand working with decorators!!

**Comment by aimeos** [comment]
Please ask questions about Aimeos only in the forum:
https://aimeos.org/help/viewtopic.php?f=15&t=4223&p=16785#p16785

The Github issues are mainly for bug reports and feature requests.
