### ISSUE TITLE
Install Issue: Cannot add foreign key constraint

### ISSUE THREAD

**Issue by cutemonster** [aimeos/aimeos#88]
First of all, I use mySql 5.7.37 and I still get **Specified key was too long** issue unless I change the database.php to the following as mentioned in doc.
```
'charset' => 'utf8',
 'collation' => 'utf8_unicode_ci',
```

At the end of the installation, I have this error
```
 SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint: ALTER TABLE users_address ADD CONSTRAINT fk_lvuad_pid FOREIGN KEY (parentid) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
```

**Comment by aimeos** [comment]
Do you install Aimeos into an existing Laravel installation?
Is you `users` table an InnoDB table?

**Comment by cutemonster** [comment]
I'm installing as new app.
The users table is not innoDB, how do I make it as default?

![image](https://user-images.githubusercontent.com/212361/161817641-d2fc7799-8a42-4602-9966-616cd955cdde.png)

**Comment by aimeos** [comment]
Maybe you can set InnoDB as default table engine in phpMyAdmin before installing Aimeos into that database.
The other option would be to change the existing tables to InnoDB and install Aimeos again from scratch without dropping the tables. In that case, the existing tables are used and missing ones added.
