### ISSUE TITLE
Issues when i run the command for demo data(php artisan aimeos:setup --option=setup/default/demo:1)

### ISSUE THREAD

**Issue by Shradhanjalisahu** [aimeos/aimeos#99]
Aimeos\Base\DB\Exception 

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("laravel"."mshop_customer_address", CONSTRAINT "fk_mscusad_pid" FOREIGN KEY ("parentid") REFERENCES "mshop_customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE):
                                        INSERT INTO "mshop_customer_address" (
                                                "firstname", "lastname", "address1", "address2", "address3",
                                                "postal", "city", "state", "countryid", "langid", "telephone",
                                                "email", "telefax", "website", "longitude", "latitude", "pos",
                                                "birthday", "mtime", "editor", "siteid", "ctime"
                                        ) VALUES (
                                                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
                                        )
                                ["6","Demo company","DE999999999","ms","","Test","User","Demo street","100","","12345","Demo city","NY","US","en","","demo@example.com","","",null,null,0,null,"2022-09-13 04:59:44","core","1.","2022-09-13 04:59:44"]

  at D:\Workspace\SAPX\myshop\vendor\aimeos\aimeos-base\src\DB\Statement\DBAL\Prepared.php:77
     73▕        {
     74▕                try {
     75▕                        $result = $this->exec();
     76▕                } catch( \Doctrine\DBAL\Driver\Exception $e ) {
  ➜  77▕                        throw new \Aimeos\Base\DB\Exception( $e->getMessage() . ': ' . $this->sql . json_encode( array_column( $this->binds, 0 ) ), $e->getCode() );
     78▕                }
     79▕
     80▕                return new \Aimeos\Base\DB\Result\DBAL( $result );
     81▕        }

  1   D:\Workspace\SAPX\myshop\vendor\aimeos\aimeos-core\src\MShop\Common\Manager\Address\Base.php:174
      Aimeos\Base\DB\Statement\DBAL\Prepared::execute()

  2   D:\Workspace\SAPX\myshop\vendor\aimeos\aimeos-core\src\MShop\Common\Manager\Base.php:119
      Aimeos\MShop\Common\Manager\Address\Base::saveItem(Object(Aimeos\MShop\Customer\Item\Address\Standard))

**Comment by Shradhanjalisahu** [comment]
How can i resolve this issues please help me out, i am struggling for long time

**Comment by Shradhanjalisahu** [comment]
Any one help me for this issues.

**Comment by aimeos** [comment]
Can you please update the Aimeos core package to 2022.07.x-dev and try again?
```
composer req aimeos/aimeos-core:2022.07.x-dev
php artisan aimeos:setup --option=setup/default/demo:1
```
